### PR TITLE
replaced internals of amu with call to FFV

### PR DESCRIPTION
**Pull request by wkotlarski**
@Expander, you wanted me to replace assertion with an `ERROR`. If we don't crash on fatal error, what should the `calculate_a_muon_impl` function return then? Other than that the code is ready. Numerical results unchanged. Relevant tests are passing. I also took into account @iolojz remark.

### CODE REVIEW

**Comment by Expander** [comment]
Many thanks, that looks good!

Sorry, you might have misunderstood me. I proposed to throw an exception of some customp type that inherits from `Error`.

**Comment by SoundSonic1** [comment]
How is `discardSMcontributions` meant to be used? It seems to be not accesible when creating the model.

**Comment by wkotlarski** [comment]
The value of `discardSMcontributions` is determined by the observale and should not be touched by the user. In g-2 we calculate an offset to the SM so we set `discardSMcontributions` in the g-2 module to `true`. While at the same time, for mu to e gamma we set it to `false` since we calculate the branching ratio.

**Comment by wkotlarski** [comment]
About the exception. Who should catch it? Currently, in g-2 Jobst throws them and catches them on the spot. Should I do the same? And then as a rescue what should the g-2 routine return as a value?

**Comment by Expander** [comment]
Good question. We may have multiple observables to be calculated (besides the spectrum) and some may fail and others not. It may be best to calculate as many observables as possible and return an "error value" if one fails.

Actually, the current approach to immediately catch the exception and return `std::numeric_limits<double>::quiet_NaN()` is not bad, although the user does not gain information about what went wrong. Probably it is also best to stick to the current interface, i.e. to not let an exception move out of `calculate_observables()`.

So, I think it would be best to do it as is currently done: Catch it inside the calculation routine and return `quite_NaN` if there is a problem.

**Comment by wkotlarski** [comment]
@Expander, is the last change ok with you?

**Comment by Expander** [comment]
Could you please replace the `std::cout` by the `ERROR()` defined in `src/logger.hpp`?

**Comment by wkotlarski** [comment]
There are 3 g-2 tests. Only the `SM` is passing. The `MRSSM2` and `munuSSM` fails as
```
test/test_MRSSM2_gmm2.cpp(65): error: in "test_amu": difference{0.000403686} between amu{-8.1729622923737651e-11} and -8.176261599534122e-11{-8.1762615995341224e-11} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(72): error: in "test_amu": difference{0.00551987} between amu{6.2643225949603516e-12} and 6.229934186618265e-12{6.2299341866182653e-12} exceeds 9.9999999999999995e-08
```
and as
```
test/test_munuSSM_gmm2.cpp(135): error: in "test_amu": difference{0.789556} between amu{2.2203047556033216e-09} and reference_value{1.2407012653192522e-09} exceeds 9.9999999999999995e-07
```

**Comment by Expander** [comment]
Many thanks for checking!

Could you please merge the `development` branch into the `feature-replace_part_of_amu_with_FFV` branch and run the tests again? It may be that things have changed recently.

**Comment by wkotlarski** [comment]
Apparently you've fixed the tests in the development in commit 4e8c5f2a811830f4dedc20a104266192d0a31d66. I think we're ready to merge.

**Comment by Expander** [comment]
Perfect, many thanks!

**Pull request merged**
