### PR TITLE
compute observables only if spectrum was generated

### PR DESCRIPTION
**Pull request by wkotlarski**
Now the observable block is not printed unless we calculate observables. This messes up with some tests.

### CODE REVIEW

**Comment by Expander** [comment]
Hmm, you've changed the condition under which the database output is written: For example, with this commit a database entry is only added if the SM and BSM pole masses are calculated. I think that is not very user friendly, because sometimes I want to only calculate BSM pole masses and have them in the output (database or SLHA).

**Comment by Expander** [comment]
Thanks for the changes!

If I understand correctly, you are now calculating the observables only if an SLHA output file is specified. I have the feeling this is a bit too restrictive, although it would work.

What about the following strategy: You revert the changes and simply modify the if condition in the (now removed) line 89.

This would look simpler to me and would have the advantage that you're not mixing the logic of calculating the observables and the SLHA output.

**Comment by Expander** [comment]
Thanks a lot!

Sorry, maybe I'm missing something, but it seems that the checks for
~~~
spectrum_generator_settings.get(Spectrum_generator_settings::calculate_sm_masses)
spectrum_generator_settings.get(Spectrum_generator_settings::calculate_bsm_masses)
~~~
are missing. :) (I thought they were essential.)

**Comment by wkotlarski** [comment]
I'm checking it. They are essential for decays, I don't remember how it was for other observables.

**Comment by wkotlarski** [comment]
For now the observables we compute don't require SM or BSM pole pole masses. And the running masses are always computed.

**Comment by Expander** [comment]
Ok, I see. :) Then please feel free to squash-and-merge this PR.

**Pull request merged**
