### PR TITLE
Remove colour indices and implement colour factors.

### PR DESCRIPTION
**Pull request by iolojz**
@wkotlarski and @SoundSonic1 please check if this works with your branches and let me know if I broke something ;)

### CODE REVIEW

**Comment by SoundSonic1** [comment]
I am getting problems with the test suite if i call

hhSelfenergyCode = NPointFunctions`CreateCXXFunctions[
	{hhSelfenergy}, {"selfenergy_hh_1loop"}, LoopFunctions -> "FlexibleSUSY"][[2]];

Is it possible to move colourFactorProjections into OptionsPattern?

**Comment by SoundSonic1** [comment]
Btw, is it possible to use `Coefficient` instead of function overloading for `ProjectColourFactor`?

[https://reference.wolfram.com/language/ref/Coefficient.html](url)

**Comment by wkotlarski** [comment]
@iolojz, for me your stuff works. But please use ``Vertices`SarahColorIndexQ`` from @jhyeon istead of ``CXXDiagrams`IsColourIndex``.

**Comment by iolojz** [comment]
The above commits should remedy your concerns. Also thanks to @SoundSonic1 for the last bugfix.

**Comment by wkotlarski** [comment]
@Expander, for me this pull request is ready to be accepted.

**Comment by Expander** [comment]
@SoundSonic1 are you also ok with this pull request?

**Comment by SoundSonic1** [comment]
@Expander yes, the pull request is fine.

**Pull request merged**
