### PR TITLE
Replacement for SARAH`Vertex

### PR DESCRIPTION
**Pull request by uukhas**
Connected to #63, #270, #271 

This PR adds one new function, named ``Cache`GetVertex``, which replaces ``SARAH`Vertex`` function. It pretends to give *the same* result as replaced function, but faster.

Before the first usage it should be "activated" with ``Get[Cache`GetVertex]``. In the end, in order to save new results ``Put[Cache`GetVertex]`` can be used. 

Also has a unit test, which checks *all non-zero* field combinations:
   1) different permutations without indices,
   2) different permutations with *default* symbolic indices,
   3) different permutations with *default* symbolic indices, where generation indices are replaced by integers,
   4) small subset of zero-vertex field combinations, in order to check the mechanism.

Some known issues and possible suggestions:
   1) We can unify zero-vertex output to  `{{<fields>}, {0, 1}}`. `SARAH` gives a lot of different zeroes, and sometimes they are "random" (= strongly depend on internal Lagrangian form), i.e. for `SSVV` vertices it is `{0,1}` and sometimes `{0,g[lt1,lt2]}`. This is bad.
   2) `SARAH SSV` vertices with momenta difference also give "random" signs in front of coefficient and Lorentz structure (and sometimes even wrong results! - look at `Vertex@{bar@Fu@{1, 1}, Fu, VZ}` for `MRSSM`, or `Vertex@{phiO, VG, phiO}` for the same model. The last example is a very bad bug, and I am going to report about it). New functions give the result, which it identical to `SARAH` expression, but when one adds integer indices, then I gave up to implement the fast evaluation, because the results are "randomly" multiplied by minus sign, so then ``SARAH`Vertex`` is called instead.
   3) Calls for two particles are not cached.

### CODE REVIEW

**Comment by Expander** [comment]
What is the speed-up that you achieve with this change?

**Comment by Expander** [comment]
Does it fix #271 ?

**Comment by uukhas** [comment]
> What is the speed-up that you achieve with this change?

Each vertex is calculated something like 100-300 times faster.
Loading time of 8k+ different vertex permutations for MRSSM of the form:
```
{{Ah, hh, VZ}, {1, 3, 2}, {gt1 -> gt1, gt2 -> gt3, lt3 -> lt2}, Plus}
```
is absolutely negligible.

**Comment by uukhas** [comment]
> Does it fix #271 ?

It depends on what you mean by fix. Now this code gives an output as SARAH does. If we want to get a normal output, then we need to be specific about its form. I think, that the best one would be the following: take the correct generic expression for vertex, then replace generic indices by given ones in the user input.

If you agree with this, then I need to modify the code slightly and the test as well.

**Comment by uukhas** [comment]
Written in a too complicated and obscure way. Relies too strongly on `SARAH` functions.

**Pull request closed without merging**
