### PR TITLE
fix: error when KernelObject is not represented in FullForm.

### PR DESCRIPTION
**Pull request by uukhas**
I noticed, that 
```
NPointFunctions`internal`GenerateFAModelFileOnKernel: errUnknownInput:
Usage:
@brief Generate the FeynArts model file on a given subkernel.

The behavior for case
1) GenerateFAModelFileOnKernel[kernel_Parallel`Kernels`kernel]
is defined only.

Call
GenerateFAModelFileOnKernel[KernelObject[1, local]]
is not supported.
Wolfram Language kernel session terminated.
```
is generated by tests. This is weird, because `KernelObject[1, local]` _has_ the head ``Parallel`Kernels`kernel`` in `FullForm`.

### CODE REVIEW

**Comment by Expander** [comment]
Thanks for catching this! @wkotlarski , are you ok with this change?

**Comment by Expander** [comment]
Does this fix the compilation of the MRSSM in the github pipelines?
https://pipelines.actions.githubusercontent.com/Td3nXzIIgCbec0fyVOJcnr5aKNucV9NEXWLidPWk4JQANr3Hmr/_apis/pipelines/1/runs/679/signedlogcontent/3?urlExpires=2020-05-05T18%3A11%3A31.5151049Z&urlSigningMethod=HMACV1&urlSignature=ZET%2FalT74Bkir5wN6wFpTUc1oHNtmy%2BueJZ54dPS8lA%3D

**Comment by uukhas** [comment]
> Does this fix the compilation of the MRSSM in the github pipelines?
> https://pipelines.actions.githubusercontent.com/Td3nXzIIgCbec0fyVOJcnr5aKNucV9NEXWLidPWk4JQANr3Hmr/_apis/pipelines/1/runs/679/signedlogcontent/3?urlExpires=2020-05-05T18%3A11%3A31.5151049Z&urlSigningMethod=HMACV1&urlSignature=ZET%2FalT74Bkir5wN6wFpTUc1oHNtmy%2BueJZ54dPS8lA%3D

If I just press this link, then I et almost nothing. How should I open it?

**Comment by Expander** [comment]
Sorry, then this was probably a temporary link. 
It said:
~~~
2020-05-05T19:05:36.1859252Z ----------------------------------------------------------------------
2020-05-05T19:05:36.1864001Z NPointFunctions`internal`GenerateFAModelFileOnKernel: [1;31merrUnknownInput[1;0m:
2020-05-05T19:05:36.1870407Z Usage:
2020-05-05T19:05:36.1870740Z @brief Generate the FeynArts model file on a given subkernel.
2020-05-05T19:05:36.1870831Z 
2020-05-05T19:05:36.1870923Z The behavior for case
2020-05-05T19:05:36.1871020Z 1) GenerateFAModelFileOnKernel[kernel_Parallel`Kernels`kernel]
2020-05-05T19:05:36.1871102Z is defined only.
2020-05-05T19:05:36.1871275Z 
2020-05-05T19:05:36.1871364Z Call
2020-05-05T19:05:36.1871456Z GenerateFAModelFileOnKernel[KernelObject[1, local]]
2020-05-05T19:05:36.1871539Z is not supported.
2020-05-05T19:05:36.1871884Z Wolfram Language kernel session [1;31mterminated[1;0m.

~~~

**Comment by uukhas** [comment]
This output is almost identical to the one I mentioned. It has the same source. The problem is that for some reason `KernelObject` is not represented internally by ``Parallel`Kernels`kernel``. As a solution I see the addition of `_KernelObject` to a meta function which causes this problem.

**Comment by Expander** [comment]
OK, thanks!

**Comment by Expander** [comment]
@wkotlarski are you ok with this change?

**Comment by uukhas** [comment]
It turned out, that there was an empty test inside `test/module.mk` which gave some errors.

**Comment by Expander** [comment]
Thank you!

**Pull request merged**
