### PR TITLE
speedup 1L decay amplitudes

### PR DESCRIPTION
**Pull request by wkotlarski**

### CODE REVIEW

**Comment by Expander** [comment]
Is the speed-up still of the order of a few percent?

**Comment by wkotlarski** [comment]
Hard to say. It's at the level that I might be seeing it where it actually doesn't exist. There might be a few % for the most complicated models and only with collier. So right now I would only merge not because of speed but if you think that this way is cleaner/might be faster in the future.

**Comment by azedarach** [comment]
This is cleaner, with less repetition than the previous multiple calls, so looks good here.

**Review by azedarach — APPROVED** [review]

**Comment by wkotlarski** [comment]
One last question @azedarach. This assumes that all calls to, lets say, C-functions within the single amplitude have the same arguments. I went through the code and this seems to be the case. Also, this seems to be confirmed by the fact that this merge doesn't change results.

**Comment by azedarach** [comment]
I think this is the case too, although all of the calls are generated within `SaveLoopIntegrals` and so it is possible to inspect the loop function calls that are required for a given diagram, right? One additional check that could be done then before updating the generated routines would be to insert a small function comparing the argument lists of the loop functions of each type that are extracted from the given diagram to make sure they are the same, or generate additional local variables as needed.

**Comment by wkotlarski** [comment]
I've added a check that counts (separately) number of A, B and C-type functions with distinct arguments and fails if it's more than 1.

**Pull request merged**
