### PR TITLE
Implements GGV, VVV and VVVV vertices in CXXDiagrams

### PR DESCRIPTION
**Pull request by iolojz**
The new vertex implementation is rather straightforward. The more extensive stuff is a unit test for SM vertices.

### CODE REVIEW

**Comment by iolojz** [comment]
This should fix bug https://github.com/FlexibleSUSY/FlexibleSUSY/issues/54.

**Comment by Expander** [comment]
Please review this pull request:
@wkotlarski
@Expander

**Comment by wkotlarski** [comment]
@iolojz, did you observe a significant slow down during compilation for the MSSM with the new stuff you added to CXX diagrams?

**Comment by iolojz** [comment]
Huh? No, that sounds weird, since no code actually uses the new vertices
yet apart from the SM unit tests. For the MSSM I havent even written a unit
test.

I can have a look at that next week.

Am Fr., 8. Feb. 2019, 14:09 hat Wojciech Kotlarski <notifications@github.com>
geschrieben:

**Comment by wkotlarski** [comment]
Could it be because since `FlexibleDecay` uses all the vertices, our `MRSSM2_vertices.hpp` file now has 100k lines?

**Comment by iolojz** [comment]
Well, I do not know about FlexibleDecay but if the file is that big you are
probably right. I can move the vertex definitions into a .cpp file - that
should improve compilation time if it is an issue.

**Comment by Expander** [comment]
Just my Senf: I would also be in favor if compilation time can be reduced, as I find this very frustrating sometimes. :)

**Comment by wkotlarski** [comment]
This definitely has to be addressed. The MRSSM now compiles > 4h. @iolojz, I checked that this is caused by `_vertices.hpp`. Your branch `feature-CXXDiagrams-new-vertices` compiles normally, but if I take my `_vertices.hpp` file and copy it onto your generated code the compilation time explodes.

**Comment by iolojz** [comment]
Alright, I moved the vertex implementations to a new `.cpp` file. This should fix your issue, would you please try again @wkotlarski ?
@Expander In `templates/module.mk.in` one should probably add `vertices.cpp.in` to a new variable `LIB@CLASSNAME@_CXXQFT_SRC` instead of just adding it to `LIB@CLASSNAME@_SRC`. But the make rules are so entangled that I am afraid to miss something if I tried to do so. Would you mind having a look?

**Comment by wkotlarski** [comment]
`concatenate.hpp` uses `std::array` but is missing an `#include <array>`

**Comment by SoundSonic1** [comment]
I am trying to understand your triple gauge boson vertex implementation.  The request to the vertex seems ambiguous because the momentum flow is not specified.

**Comment by iolojz** [comment]
Could you be more specific? Imho, it is taken care of by
```
expr = Switch[Thread[Expand /@ {vertex[[2,2]], - vertex[[2,2]]} == Expand[
				SARAH`g[lIndex1, lIndex2] * (SARAH`Mom[sortedIndexedFields[[1]], lIndex3] -
					SARAH`Mom[sortedIndexedFields[[2]], lIndex3]) +
				SARAH`g[lIndex2, lIndex3] * (SARAH`Mom[sortedIndexedFields[[2]], lIndex1] -
					SARAH`Mom[sortedIndexedFields[[3]], lIndex1]) + 
				SARAH`g[lIndex1, lIndex3] * (SARAH`Mom[sortedIndexedFields[[3]], lIndex2] -
					SARAH`Mom[sortedIndexedFields[[1]], lIndex2])]],
				
				{True, _}, expr,
				{_, True}, - expr,
				_, Print["CXXDiagrams`VertexFunctionBodyForFieldsImpl[]: Unknown Lorentz \
structure in vertex: " <> ToString[vertex]]; Quit[1]];
```

where `expr` is either left as it is or set to `-expr` depending on the momentum flow.

**Comment by wkotlarski** [comment]
`CXXNameOfField` accepts namespace through an optional argument but for conjugated/bared fields this prefix is not set for a bar/conj symbol. Shouldn't `CXXNameOfField` for bared fields be
```
CXXNameOfField[SARAH`bar[p_], OptionsPattern[{prefixNamespace -> False}]] :=
  "typename " <> If[OptionValue[prefixNamespace] === False, "", OptionValue[prefixNamespace]<>"::"]  <> "bar<" <> CXXNameOfField[p, prefixNamespace -> OptionValue[prefixNamespace]] <>
  ">::type";
```
and analogusly for `conj` ones?

**Comment by wkotlarski** [comment]
There's a problem with gcc and vertices. For MRSSM `MRSSM_vertices.cpp` has around 100k lines. This single file compiles around 50 minut with `gcc` and few seconds with `clang`.

**Comment by Expander** [comment]
@iolojz Unfortunately there is a merge conflict now, after I've merged #70. Would you mind having a look what's causing the conflict?

Besides this, do you have an idea what can be done to speed-up the compilation with `gcc`?

**Comment by iolojz** [comment]
The merge conflict is resolved. I am actually currently looking into it. My first guess was that somehow gcc is slow on template specializations. So I replaced all templated parts of `cxx_qft/MRSSM2_vertices.cpp` with normal function names - however, `gcc` still takes ages it seems :/
This is really bad, because it means that gcc is slow on compiling stuff like:

```
ScalarVertex VertexImpl_conjSRumSuSRumconjSu(
   const std::array<int, 4>& indices, const context_base& context)
{
   const int gt2 = indices[0];
   const int ct2 = indices[1];
   const int gt4 = indices[2];
   const int ct4 = indices[3];
   const auto g1 = MODELPARAMETER(g1);
   const auto g2 = MODELPARAMETER(g2);
   const auto ZU = MODELPARAMETER(ZU);

   const std::complex<double> result = 0.05*KroneckerDelta(ct2,ct4)*((Sqr(g1) + 5*Sqr(g2))*SUM(j1,0,2,Conj(ZU(gt2,j1))*ZU(gt4,j1)) - 4*Sqr(g1)*SUM(j1,0,2,Conj(ZU(gt2,3 + j1))*ZU(gt4,3 + j1)));

   return {result};
};
```

which seems hard to simplify further...

**Comment by Expander** [comment]
Hmm, the code snippet you've shown actually looks very neat and simple.

I guess it cannot be that `result` or any of the local definitions are the reason, because we have much more complicated of those expressions in FS that compile very fast.

**Comment by iolojz** [comment]
@wkotlarski regarding your `CXXNameOfField[]` question: This is not necessary (as long as everything takes place inside the `@ModelName@_cxx_diagrams` namespace because `bar<>` and `conj<>` are exported to that namespace (see: templates/cxx_qft/fields.hpp.in:157-158).

**Comment by iolojz** [comment]
@Expander Yes, I also do not believe the function bodies are the problem. I also strongly doubt it to be the return types though, their constructors are always extremely simple.

**Comment by iolojz** [comment]
It seems that chopping up the vertices file into smaller pieces fixes the problem... So this is probably some exponential complexity thing in gcc. One could cap the file size to be e.g ~10000 loc and split the vertices over multiple files. This is easy enough from the codegen perspective but does not fit well into FS at all:
- The `CreateXXX[]` idiom in `meta/FlexibleSUSY.m` where a list of files is passed as an argument
- The makefiles do not really support it either

**Comment by Expander** [comment]
Well, there are examples in FS, where longish expressions are split into multiple files. One is for example the beta functions, see for example `WriteRGEClass[]`. This function generates multiple files (based on the file template `susy_beta_.cpp.in`) and the corresponding makefile module `beta.mk.in`. The latter is included in the `module.mk` file and contains a list of all generated files.

**Comment by Expander** [comment]
Btw, the splitting of the beta functions into multiple files had the same cause: The compilation for some models took ages (and swapped).

**Comment by iolojz** [comment]
I see. That is good! I will try to cook up something tomorrow :)

**Comment by Expander** [comment]
Thanks a lot!  :)

**Comment by iolojz** [comment]
Sorry, for not making it yesterday. I have caught quite bad a cold :/
@wkotlarski Could you check, if it solves your problem of extremely long compile times?

**Comment by wkotlarski** [comment]
This seems to solve the problem.

**Comment by Expander** [comment]
Perfect, many thanks! Shall I merge it?

**Comment by wkotlarski** [comment]
Yes.

**Pull request merged**
