### PR TITLE
TestWithMessage and PureEvaluate are added.

### PR DESCRIPTION
**Pull request by uukhas**

### CODE REVIEW

**Comment by Expander** [comment]
Many thanks for your contribution!

Concerning your function names:

* Your function `TestWithMessage` seems to abort the calculation if an error has occured. In this sense, it should be named `AssertWithMessage` or similar, because it is not a simple test, but an assertion.

* Your function `PureEvaluate` evaluates an expressions and aborts if a message is generated (probably due to an error or warning). In this sense the function may be named as `EvaluateOrQuit` or `EvaluateOrQuitIfError` or `StrictEvaluate` or similar.

What do you and the others think? @pathron @wkotlarski

**Comment by uukhas** [comment]
Dear @Expander, 
- the name `AssertWithMessage` already exists, following the logic of the second function I suggest `AssertOrQuit`;
- the name `EvaluateOrQuit` would be nice in coherence with the first name.

**Comment by Expander** [comment]
Dear @uukhas ,

ok, then I'd vote for `AssertOrQuit` and `EvaluateOrQuit`, respectively. Could you please change these function names?

**Comment by uukhas** [comment]
Dear @Expander,

these are the changes. 
About Mathematica 9: I will check, but it will require some time. For Mathematica 12 these functions work.

**Comment by Expander** [comment]
Many thanks for your changes!

As long as these functions as not used in the meta code, the compatibility with Mathematica 9 is not an issue. However, as soon as they are used, we must ensure that they work with Mathematica >= 9.

So, if you find the time, please check their compatibility with Mathematica 9 before they get used. :)

**Comment by Expander** [comment]
Besides this, is your code ready to be merged?

**Comment by uukhas** [comment]
Dear @Expander, yes. 
They are working and doing what are they suppose to do.

**Pull request merged**
