### PR TITLE
Fix broken cxxdiagrams/npointfunctions tests

### PR DESCRIPTION
**Pull request by wkotlarski**
This branch isolates broken tests until they are fixed.

### CODE REVIEW

**Comment by wkotlarski** [comment]
Error from clang
```
malloc_consolidate(): invalid chunk size
[1]    16990 abort (core dumped)  test/test_SM_npointfunctions.x
```
from gcc
```
corrupted size vs. prev_size in fastbins
[1]    10457 abort (core dumped)  test/test_SM_npointfunctions.x
```
This error happens ~50% of times.

**Comment by Expander** [comment]
I've got another idea: Maybe you can run `clang-tidy` on the source file?
~~~
clang-tidy test/test_SM_npointfunctions.cpp -checks='*' -- -Isrc [...]
~~~
Maybe this reveals some hints to the issue

**Comment by wkotlarski** [comment]
I've fixed some warning, but to no avail [clang_tidy.txt](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4546037/clang_tidy.txt).

**Comment by Expander** [comment]
Yes, `clang-tidy` is a bit noisy, and criticizes the actual C++ standard in some points. :)

Non of these warnings looks critically. (You may disable some that are of no interest here, like `fuchsia-default-arguments-calls` or so.)

**Comment by wkotlarski** [comment]
@Expander, I have no idea why but `-D_GLIBCXX_USE_CXX11_ABI=0` fixes also the `test_SM_npointfunctions` test. It does break other tests though.

**Comment by Expander** [comment]
If you find the time, could you try to merge `development` into this branch? There, the mentioned tests have been changed and I'm curious if this has some effect on this issue.

**Comment by wkotlarski** [comment]
@Expander, do I understand correctly that you did reinstate those tests already? If so, than I think this PR does not have anything left and can be closed without merge.

**Comment by Expander** [comment]
> @Expander, do I understand correctly that you did reinstate those tests already? If so, than I think this PR does not have anything left and can be closed without merge.

Hmm, not that I'm aware of. It may have happened accidentally, but I'm not sure how.

**Comment by wkotlarski** [comment]
Ah, yes. It's @uukhas fault. Because of course it is :D It was done in PR #148. Seems @uukhas overwrote some commits on dev branch. We should check if something important was not lost.

**Comment by Expander** [comment]
I've just checked it: No test has been lost.

**Pull request closed without merging**
