### PR TITLE
Bugfix: fix SM cxxvertices compilation error

### PR DESCRIPTION
**Pull request by Expander**

### CODE REVIEW

**Comment by Expander** [comment]
fixes #598

**Comment by wkotlarski** [comment]
I'm not sure about this naming convention (I've struggled with it myself). Putting `SM` instead of `standard_model` makes sense in that this test depends on the `SM`. But is also misleading as to the function of this test. Because its purpose is not to test the `SM`. It's to test against `SM`.

**Comment by wkotlarski** [comment]
What if we have a `SM` test for a given feature. For example, we might want to test `cxxvertices` in the `SM` ( we actually do, but for whatever reason we call it `SM_cxxdiagrams`). Should the `standard_model` tests be merged into one file with the `SM` ones?

**Review by wkotlarski — APPROVED** [review]

**Comment by Expander** [comment]
Hmm, I'm not 100% sure what rule to follow. Initially my approach was like this: Let's say we create a model, say `CMSSM` and want to test that the corresponding generated code coincides with existing results (literature results or existing implementations). Then I had created a test with the name `test_CMSSM_feature.cpp`. The result was that in the `test/module.mk` we had very readable statements of the form:
~~~
ifeq ($(WITH_CMSSM),yes)
TEST_SRC += test_CMSSM_feature.cpp
endif

$(DIR)/test_CMSSM_feature.x: $(LIBCMSSM)
~~~
Initially I had thought that a similar rule applies to the generated `SM` model.

Now I have the feeling that the `SM` and the pre-generated `standard_model` are somehow equivalent and there are some tests that test the two models against each other. In this case I'd propose the following rule (please object if you think that does not make sense):
1. If a test tests a feature of a *generated* model (e.g. the `SM` or the `CMSSM`), we should call it `test_SM_*` etc. 
1. If a test tests a pre-generated model (e.g. the pre-generated `standard_model`) and is independent of a generated model, we should call it `test_standard_model_*`.

The first rule would be consistent with most tests that we currently have. It would also lead to these "readable" lines in `test/module.mk`. In particular, such tests would always be wrapped in `ifeq` statements in `test/module.mk`.

The second rule would lead to tests that are independent of any generated code and could thus always be built and run. They would thus not be wrapped in `ifeq` statements in `test/module.mk` as above, i.e.
~~~
ifeq ($(WITH_<model>),yes)
TEST_SRC += test_<model>_*.cpp
endif

$(DIR)/test_<model>_feature.x: $(LIB<model>)
~~~
Another consequence of the first rule would be: If we test the generated `SM` against the pre-generated `standard_model`, we would call the test `test_SM_standard_model_*`. I.e. the test would be of the form `test_SM_*` and would be wrapped in an `ifeq` statement. The test name would furthermore be of the form `test_<model1>_<model2>_*` such as other tests that compare two models.

What do you think?

**Pull request merged**
