### PR TITLE
replace muon pole mass in a_mu

### PR DESCRIPTION
**Pull request by wkotlarski**
This addresses problem discussed in #82. Since we need an access to muon mass from the input file an `softsusy::QedQcd` needs to be passed around.

### CODE REVIEW

**Comment by Expander** [comment]
Could you please include `lowe.h` in the .cpp file only? (I'd like to include as few headers in headers as possible, in order to keep compile time as small as possible.) In the .hpp file please just forward declare `softsusy::QedQcd`, like so:
~~~
namespace softsusy {
   class QedQcd;
} // namespace softsusy
~~~

**Comment by wkotlarski** [comment]
Done. I didn't want to overwrite history since someone might have already checked out this branch but I'd suggest to squash those commits when accepting this pull request.

**Comment by Expander** [comment]
Many thanks, this is perfect!

Do all current tests pass? Would you mind adding new unit tests for the models where you fund the issue?

**Comment by Expander** [comment]
Sorry, could it be that the file `test/test_munuSSM_gmm2.cpp` has not been added?

**Comment by wkotlarski** [comment]
I have some trouble setting a unit test that would correspond to `LesHouches.in` file for the `munuSSM`. I'd like to get from my test the same number I get from running full `FS` on the input file. I don't know how to set it up though. Could you have a look?

**Comment by Expander** [comment]
One option would be to create a `.sh` test, where you read in the SLHA file and check the numbers you get out. Would that be an option?

**Comment by wkotlarski** [comment]
I just look into one of them. I'd like to avoid it as much as possible. What's wrong with this 2 scale solve I've setup up. Shouldn't I've get the same output as from running `FS` on the input file?

**Comment by Expander** [comment]
The reason for the deviation is most probably, that not all input parameters are set as defined in the standard SLHA input file. You may do this like so:
~~~
char const * const slha_input = "
MODEL
   12   1000
[...]
";

std::stringstream istr(slha_input);

munuSSM_slha_io slha_io;
slha_io.read_from_stream(istr);

// extract the input parameters
softsusy::QedQcd qedqcd;
munuSSM_input_parameters input;

try {
   slha_io.fill(qedqcd);
   slha_io.fill(input);
} catch (const Error& error) {
   ERROR(error.what());
   return EXIT_FAILURE;
}
~~~

**Comment by Expander** [comment]
Sorry, I forgot to say that C does not like these kind of line breaks.
Please either use a raw string (works in gcc):
~~~
char* = R"Line 1
Line 2";
~~~
Or escape the hidden newline character:
~~~
char* = "Line 1\
Line 2";
~~~

**Comment by Expander** [comment]
I've pushed the branch fix-replace_muon_pole_mass_in_amuon where the textural SLHA input is read and passed to the `setup_munuSSM()` function.

**Comment by wkotlarski** [comment]
In my branch I figured out how to set stuff up from inside the test. I'm getting a small numerical differences compared to normal `FS` run. Is the same true for your method?

**Comment by Expander** [comment]
Sorry, I've not checked my changes so far, I just made them compile.

**Comment by Expander** [comment]
In commit ab533dc598fa80e193ba045703c6e8a4ad88a8b6 I've now fixed the test. It does not fail on my machine. How big is the deviation that you get?

**Comment by wkotlarski** [comment]
I works, perfect. But can you tell me why what I did does not work? I was thinking how should we structure tests for observables while we add more and more of them. I'd like my solution more as it's more flexible but I don't know why it doesn't work.

**Comment by Expander** [comment]
If I understand your initial problem correctly, you did
* default construct the `QedQcd` object
* default construct the `Spectrum_generator_settings`
* initialize the `munuSSM_input_parameters` object correctly

The only thing I added was to feed the SLHA input to the SLHA reader, then fill (read) the `QedQcd` and `Spectrum_generator_settings` objects from it, and finally use them to run the spectrum generator. So, I would conclude that there was a simple mismatch of the SM input parameters (`QedQcd`) and `Spectrum_generator_settings` in your setup compared to the SLHA file that you did use to calculate the value of g-2 for the test.

Could that be?

**Comment by Expander** [comment]
If I see your last commit correctly, you've also fixed the test by setting the SM input parameters to the values used to calculate the "fixed" value of g-2 written in the test, right?

**Comment by wkotlarski** [comment]
Yes, but there is still a relative difference of `0.0003` between the g-2 value from a test and from the SLHA output. But, as you say, they should be equivalent.

**Comment by wkotlarski** [comment]
Solved. Turns out that the `beta_zero_threshold` option is important (even though I have no idea what it does). Also, I've noticed that some variables have to be set twice. For example, the muon mass can be set as
```
qedqcd.setPoleMmuon(1.056583570e-01);
qedqcd.setMass(softsusy::mMuon, 1.056583570e-01);
```
and it seems that both of them are needed. Can you comment on that?

**Comment by Expander** [comment]
> Also, I've noticed that some variables have to be set twice. For example, the muon mass can be set as [...] and it seems that both of them are needed. Can you comment on that?

~~~
setMass(mMuon, <value>); // sets the running muon mass in SM
setPoleMmuon(<value>); // sets the muon pole mass
~~~

The muon pole mass must be set to the given input value, and the running mass is an estimate of the MS-bar mass in the SM with 2 lepton flavours (and only 3 quark flavours).  (The running SM mass is just used as an initial guess for the calculation of the running mass in the considered model.)

It surprised me, that you need to set the running mass but I found why: There is a bug in the function
~~~
double muonPhysicalMass(const softsusy::QedQcd& qedqcd)
{
   // this should return the pole mass
   return qedqcd.displayMass(softsusy::mMuon);
}
~~~
Currently the function seems to return the running mass (in the above defined scheme), which is not what we want. It should return:
~~~
double muonPhysicalMass(const softsusy::QedQcd& qedqcd)
{
   return qedqcd.displayPoleMmuon();
}
~~~

**Comment by wkotlarski** [comment]
Aren't both masses set to the same thing in `librarylink.cpp` 
```
qedqcd.setMass(softsusy::mMuon, pars[c]);
qedqcd.setPoleMmuon(pars[c++]);
```
That's why I though they are the same.

**Comment by wkotlarski** [comment]
Also, what about `setAlpha` and `setAlphaEmInput` (and similarly for strong coupling) which seems to have similar syntax?

**Comment by Expander** [comment]
These masses are the same in the sense
~~~
m_muon(MS-bar, SM, Q = 2GeV) = m_muon(pole)
~~~
see the function `QedQcd::to()`. However, you are probably using the `QedQcd` object at the scale `Q = MZ`, at which the running muon mass is different from the one at `Q = 2 GeV`.

The same logic applies for alpha: The input value is `alpha_em(MS-bar, SM(6), Q = MZ)`. The value of `alpha_em` that you extract by calling `displayAlpha(ALPHA)` is the one at the scale `Q` of the `QedQcd` object.

**Comment by wkotlarski** [comment]
Ok, now I understand. So which solution do you prefer:
1.  pass entire input as a string (yours)
2. setup parameters and generator by calling appropriate internal functions (my)

**Comment by Expander** [comment]
I'm don't have a very strong opinion, but I'd slightly tend to the string-like (SLHA) input option, because then one sees the direct connection to the actual call of the spectrum generator at the command line.

Btw. in my branch I've used a "raw string", see (6) at
https://en.cppreference.com/w/cpp/language/string_literal .  This makes the SLHA string input very readable, because one does not need to escape lines or add line breaks.

**Comment by wkotlarski** [comment]
Dear @Expander, the branch is ready to be merged. Thanks for all your work.

**Comment by Expander** [comment]
Thank you!

**Comment by Expander** [comment]
Shall I squash and merge it, or would a plain merge be ok with you?

**Comment by wkotlarski** [comment]
I would squash it. There was a lot of back and forth while in the end the change is simple and linear.

**Pull request merged**
