### PR TITLE
is_zero version for complex numbers

### PR DESCRIPTION
**Pull request by wkotlarski**
This is a variant of the code prepared by Dylan. It extends `is_zero` to work on complex numbers. I don't think it's currently used anywhere but since we have it and it doesn't cost anything, whould you be ok with including it into FS?

### CODE REVIEW

**Comment by Expander** [comment]
I'm wondering, why the current implementation should not be used with complex numbers? `std::abs` is overloaded for `std::complex<T>`,
https://en.cppreference.com/w/cpp/numeric/complex/abs

It seems the difference is, that using the current implementation one checks if the number is within a circle of a certain radius around zero, while the proposed new implementation checks if the number is within a square around zero, right?

**Comment by wkotlarski** [comment]
The problem is that comparison operator doesn't work for `T` and `complex<T>`.

**Comment by Expander** [comment]
Ah, yes, of course! :) I.e. `prec` should be of a scalar type then.
Please feel free to merge it!

**Comment by wkotlarski** [comment]
Thanks!

**Pull request merged**
