### PR TITLE
Mw calculation with decoupling property

### PR DESCRIPTION
**Pull request by Expander**
Written by M. Bach and D. Stöckinger

### CODE REVIEW

**Comment by Expander** [comment]
@wkotlarski would you mind having a look at the changes? In particular the `test/test_MRSSM2_l_to_lgamma.x` test?

**Comment by SoundSonic1** [comment]
@Markus-Bach confirmed to me that this is the most recent version.
Does this implementation replace the mW calculation for all the models by default or do you have to turn it on?

**Comment by Expander** [comment]
Many thanks for asking him!

The pull request applies to all models automatically (it does not have to be activated). It is a non-optional replacement for the old W mass calculation. The reason is, that Markus has changed the Weinberg angle class, which does the calculation of MW for all models.

**Comment by wkotlarski** [comment]
@uukhas is making changes to interface to loop functions. This also concerns internal loop functions. I assume that mW calculation relies on them. Should this pull request be then accepted before @uukhas changes?

**Comment by Expander** [comment]
Yes, this should definitely be merged first.

**Comment by Expander** [comment]
I asked Dominik about it and he had no opinion on whether we should publish this calculation or not.

**Comment by Expander** [comment]
Shall we squash-and-merge the branch?

**Comment by wkotlarski** [comment]
Sorry @Expander. I missed your message. Yes please.

**Pull request merged**
