### PR TITLE
Bugfix: Ensure user-chosen order of goldstone boson / scalar bosons in decays

### PR DESCRIPTION
**Pull request by Expander**

### CODE REVIEW

**Comment by Expander** [comment]
fixes #545

**Comment by wkotlarski** [comment]
Are you sure that this bug influences only decoupling models? Because the non-decoupled model that we pass to decays suffer from the same problem.

**Comment by Expander** [comment]
In principle you are right. However, I vaguely remember that I should be careful with porting this change to the 'normal' model, because there may be some cases where a strict less-than ordering is required. (I have to see what where this came up.) Initially we've only reordered the masses for the SLHA output, I think.

**Comment by wkotlarski** [comment]
Then there's a problem with path 2
```cpp
const int flag = 1;
auto dec_model = [&] () -> std::unique_ptr<
   MRSSM2_mass_eigenstates_interface> {
      switch (flag) {
         case 1: {
            auto dm = std::make_unique<
               MRSSM2_mass_eigenstates_decoupling_scheme>(model.get_input());
               ...
               break;
         }
         case 2:
            return std::make_unique<MRSSM2_mass_eigenstates>(model);
            break;
         default:
            throw SetupError("flag value is not supported");
   }
}();
```
I would add the following then
```cpp
case 2:
   model.reorder_DRbar_masses();
   return std::make_unique<MRSSM2_mass_eigenstates>(model);
```
Are you ok with this?

**Comment by Expander** [comment]
> Are you ok with this? If yes, I'll make a commit to this branch.

Yes, please do this!

**Review by wkotlarski — APPROVED** [review]

**Pull request merged**
