### PR TITLE
fixed some -Wfloat-equal warnings

### PR DESCRIPTION
**Pull request by wkotlarski**

### CODE REVIEW

**Comment by Expander** [comment]
Many thanks! Please feel free to merge it.

**Comment by wkotlarski** [comment]
Some comments. This does not remove all such warnings. Some come from `eigen` itself. And because it's a header only library, their warnings are our warnings. Some come from the dilog, trilog, etc. This I didn't touch since it's a copy of your polylog code. It's up to you if you want to do something with it. There were I think two files were such comparison happens in a header. This I didn't know what to do with. I don't want to include `numeric2.hpp` in a header but I also cannot add new definition of `is_zero`. Finally, there are errors coming from `SOFTSUSY` in tests. This I understand is a copy of `SOFTSUSY` for tests so I didn't change it. All in all, because of all of this I also don't recommend to always compile with `-Wfloat-equal` but checking it from time to time is useful.

**Comment by Expander** [comment]
Yes, I'm aware of the warnings from the `polylogarithm` package, but these are false-positives. Not all floating point comparisons via `a == b` are bad. In particular they are not bad, if the author carefully thought about the possible minimal deviations and their origin. In case of the `polylogarithm` package, care was taken to properly treat the case where `a == b` is not true and that the numerics is stable there.

Actually, your proposed changes in `linalg2.hpp` may also fall into this category: The code pieces that throw the warning have been copied from LAPACK and may have been well tested and thought through and we may break something if we change it. But I'm not sure here.

**Comment by wkotlarski** [comment]
I wasn't sure about the lapck one. I'll revert it.

**Comment by Expander** [comment]
Many thanks! That looks good to me now.

**Pull request merged**
