### PR TITLE
Reduce compile time by explicit template instantiations

### PR DESCRIPTION
**Pull request by Expander**
I found that the compilation time of `*_mass_eigenstates.cpp` could be reduced by pre-instantiation of often used diagonalization routines.

@wkotlarski if you find the time at some point, would you mind checking if this improves the compile time on your machine?

### CODE REVIEW

**Comment by wkotlarski** [comment]
`clang++` version `10.0.0`. Meta + compilation times (single core):
```
Original: make  29641,41s user 71,19s system 98% cpu 8:21:25,10 total
New:
```
I don't have a fastest computer in the world like all those master students but it's not a potato either.
The longest one is
```
Building model_specific/MSSM_thresholds/mssm_twoloop_as.o
```
The second longest one
```
Building model_specific/MSSM_thresholds/mssm_twoloop_mtau.o
```

**Comment by Expander** [comment]
Sorry, the `New:` value may have been lost. :)

**Comment by wkotlarski** [comment]
I'm working on it ;)

**Comment by wkotlarski** [comment]
It's still going. So it might be better, but it still takes hours to compile `mssm_twoloop_as`.

**Comment by wkotlarski** [comment]
New result
```
make  28896,45s user 64,83s system 98% cpu 8:10:30,09 total
```

**Comment by Expander** [comment]
Many thanks for testing! So, for your whole build this is a speed-up of 3%, which seems negligible.
It seems more important to try to speed-up the compilation of `mssm_twoloop_as`. I'll see what I can do here. :)

**Pull request closed without merging**
