### PR TITLE
added JSON library

### PR DESCRIPTION
**Pull request by wkotlarski**
In the `CMSSMCKM` it produces the following output
```json
{    
    "basis": "flavio",    
    "eft": "WET",    
    "scale": 876.2250734853238,    
    "values": {    
        "C7_bs": {    
            "Im": 3.9190768398702315e-05,    
            "Re": 0.0021474684132679373    
        },    
        "C7p_bs": {    
            "Im": 9.127367183615244e-07,    
            "Re": 5.001331845142643e-05    
        },    
        "C8_bs": {    
            "Im": 0.0004147620437756534,    
            "Re": 0.022707082248790932    
        },    
        "C8p_bs": {    
            "Im": 9.618008326694857e-06,    
            "Re": 0.0005265592401546519    
        }    
    }    
}
```
I have chosen to indent the output with 4 spaces.

### CODE REVIEW

**Review by uukhas — APPROVED** [review]
This header library is a very huge one!
And the C++ expressions are so nice.

I would like to have it to speed up the code development.

**Comment by uukhas** [comment]
If I am not mistaken, this `json.hpp` is the copy of `single_include/nlohmann/json.hpp` file. 

@wkotlarski, what do you think about having some `sh` script, which could update this header library if needed?

It might look like this `update-json`:
```bash
[ -d 'nlohmann' ] && [ -f 'nlohmann/json.hpp' ] && rm -rf 'nlohmann'
wget -P  nlohmann  -- https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp
```

**Comment by wkotlarski** [comment]
Maybe this could be somehow automatized with github actions. But in any case, I'd used [this](https://github.com/nlohmann/json/releases/latest/download/json.hpp) link (we should not pull directly from development but only releases).

**Comment by Expander** [comment]
Very nice!

**Review by Expander — APPROVED** [review]

**Pull request merged**
