### PR TITLE
update required Mathematica version to 10

### PR DESCRIPTION
**Pull request by Expander**
because the symbol `StringPadRight` seems to be defined only from version 10 onward.

### CODE REVIEW

**Comment by wkotlarski** [comment]
According to [this](https://reference.wolfram.com/language/ref/StringPadRight.html) `StringPadRight` was introduced in 10.1, not 10.0.

**Comment by Expander** [comment]
Ah, thanks!

**Review by wkotlarski — APPROVED** [review]

**Comment by wkotlarski** [comment]
Should we also update the draft of the paper?

**Comment by Expander** [comment]
> Should we also update the draft of the paper?

Yes, I think that would be good.

**Comment by wkotlarski** [comment]
Done.

**Comment by Expander** [comment]
Thanks!

**Comment by Expander** [comment]
I'll wait for the merge until all tests have passed.

**Comment by wkotlarski** [comment]
Should we also modyfy the `README` and add this info to the changelog?

**Comment by Expander** [comment]
Oh, yes! I think the `README` is already taken care of.

**Comment by wkotlarski** [comment]
Ah, yes, sorry. I constantly accidentally look at main instead of development.

**Pull request merged**
