### PR TITLE
Fix ParticleQ

### PR DESCRIPTION
**Pull request by Expander**
ParticleQ is already used by SARAH.

### CODE REVIEW

**Comment by wkotlarski** [comment]
```mathematica
IsSMParticle /@ (AntiField /@ GetParticles[])
```
returns
```mathematica
{True, False, False, False, True, True, True, True, True, True, \
False, False, False, False, False, False}
```
Is this what you want?

P.s. @uukhas, does this function do what you want now?

**Comment by Expander** [comment]
Certainly not. The incorrect treatment of anti particles may also be an issue for other helper functions. I'll have a look and push further fixes to this branch.

**Comment by uukhas** [comment]
Maybe, quite late, but the function is not working yet because of **SARAH's AntiField[]**, or, more precisely, because of **SARAH's FermionQ[]**.
Example:

 ```
GetParticles[EWSB];
SARAH`AntiField /@ %
TreeMasses`ParticleQ /@ %
SARAH`FermionQ[Fe]
TreeMasses`IsFermion[Fe]
```

gives conj[fermions] sometimes
```
 {VG, bar[gG], conj[Hp], bar[Fv], Ah, hh, VP, VZ, gP, gZ, conj[gWp], conj[gWpC], conj[Fd], conj[Fu], conj[Fe], conj[VWp]}
 {True, False, False, False, True, True, True, True, True, True, \
 False, False, False, False, False, False}
 False
 True
```

**Comment by wkotlarski** [comment]
Also, just to not forget about it, usage message 
```
returns True if argument is a particle, False otherwise
```
is ambigious. Is anti-particle a particle? Maybe something like
```
returns True if argument is a particle or antiparticle, False otherwise
```
would be more precise.

**Comment by Expander** [comment]
@uukhas would you mind filing a bug report for ``SARAH`FermionQ`` including the simple example that you gave to reproduce the fix?

In the meantime I think we should avoid using `AntiField` if it returns non-sense sometimes. We may invent our own function `FSAntiField`. @wkotlarski what do you think?

**Comment by uukhas** [comment]
@Expander, I was looking for a source of the problem. Here it turned out that the root is ```SARAH`FermionQ[]```, which leads to incorrect results. Also, it makes ```SARAH`AntiField``` useless because of this problem.

In the same time ```TreeMasses`Is<something>Q[]``` work correct (at least for me and so far), so the creation of ```FSAntiField[]``` would be nice.

**Comment by wkotlarski** [comment]
There's a lot of places where we use `AntiField`. If it's `SARAH` error, shouldn't we fix it upstream with `SARAH`?

**Comment by Expander** [comment]
@wkotlarski of course this needs to be fixed upstream! :) However, as long as there's no official fix upstream, we have to work around this bug in some way. I'd propose to replace `AntiField -> FSAntiField` which works around this bug. Later, when the bug is fixed upstream, we may simply set `FSAntiField[f_] := AntiField[f]`.

**Comment by Expander** [comment]
@uukhas Many thanks for your help!

One question, though: Do you say that all `Is*[]` functions work as expected in FS? I'm a bit surprised, because I'm not sure if `IsSMParticle[]` for example treats anti-fields correctly.

**Comment by Expander** [comment]
Damn, I cannot file a bug report in the SARAH forum, because it is about to be moved/deactivated due to Florian leaving physics. So, we definitely need a replacement for `AntiField`.

**Comment by uukhas** [comment]
@Expander No-no-no, by **so far** I meant ```TreeMasses`IsScalar[]```, ```TreeMasses`IsFermion[]```, ```TreeMasses`IsVector[]```. 
...Yes, this is not many at all but at least they are good) Sorry for this confusion.

**Comment by Expander** [comment]
@uukhas You are right, they work correctly. I've added tests for all of them to be sure. :)

**Comment by Expander** [comment]
@wkotlarski All the tests pass with the `FSAntiField` function. I guess we should use this function at other places too to ensure that everything is consistent. What do you think?

**Comment by wkotlarski** [comment]
Agree. I'll change our code.

**Comment by Expander** [comment]
Perfect, many thanks! Shall I merge this pull request then?

**Comment by wkotlarski** [comment]
I cannot test it as I'm on an airport but I don't think there should be any problems on my side. Please merge!

**Pull request merged**
