### PR TITLE
increase C++ language version to C++14

### PR DESCRIPTION
**Pull request by Expander**
I would like to propose to increase the required C++ version to C++14.

# Advantages

In our code base I've stumbled upon several points where some C++14 features would yield to better optimized code or simpler expressions.

Examples:

* If the helper functions in `src/numerics.cpp` would be marked as `constexpr`, the assembly code for the 1-loop functions would be better optimized. The reason is that a `constexpr` function can be assumed to be "pure", i.e. has no side effects, which allows the compiler to do some more optimizations.
* The helper class `Set_spectrum` (defined in `src/slha_io.hpp`) could be removed. The function `@ModelName@_slha_io::set_spectrum` (defined in `templates/slha_io.hpp.in`) could use a local generic lambda instead. (Note that lambdas can be well optimized by current compilers.)

# Disadvantages

We would need to increase the required compiler versions to:

* g++ >= 5.0.0
* clang++ >= 3.8.1
* icpc >= 17.0.0

These g++ and clang++ versions are available on all major current linux distributions (debian, ubuntu, fedora). An exception is Scientific Linux, which currently only ships g++ 4.8.5 (and not clang).

### CODE REVIEW

**Comment by Expander** [comment]
Please review this pull request:
@pathron 
@azedarach 
@wkotlarski
@iolojz

**Comment by pathron** [comment]
To be honest I am worried that this will make it hard to update FS in GAMBIT, because GAMBIT normally aims to support the latest SL.  Let me discuss this with some GAMBIT people and get back to you.

FWIW just supporting the latest versions of Ubuntu, Fedora and Debian is not sufficient as plenty of potential users won't have the latest OS and won't want to update.  Looks like the only supported Ubuntu that doesn't have gcc-5.0 or higher is trusty tahr and that gets dropped this April so from that perspective its probably OK anyway.

**Comment by pathron** [comment]
RHEL 8 is only out in beta so looking at the lease patterns of SL https://en.wikipedia.org/wiki/Scientific_Linux#Release_history and RHEL https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#RHEL_8 I guess it could be another year or more until we see SL 8.

**Comment by Expander** [comment]
Hi Peter,

thanks for discussing this in the GAMBIT collaboration!

So, the latest SL is 7, which has only gcc 4.8.5, which is a very old version. TBH, on all SL installations that I've seen so far (IKTP, DESY) there was always a local installation of a more recent gcc version. :)

**Comment by iolojz** [comment]
I am much in favour of moving to c++14 as it provides more modern and safe utilities such as `std::make_unique()` etc. I do not know about the equipment of the userbase of FS though, so my opinion probably should not count ;)

**Comment by pathron** [comment]
So I sent the email to GAMBIT core mailing list and we will see what comes out of that.

**Comment by pathron** [comment]
So GAMBIT has agreed compiler limits can be pushed up in near future versions.   So we can just do this now if we wish to.  Only downsides are: 
I) current incompatibility with Scientific Linux defaults 

ii) any package containing suspect (which includes micrOmegas and SUSHIT) need to be compiled with a lower Intel compiler version so user would need two different Intel compilers (or g++) to interface them.  But I think it’s not a big issue - FS is fast with g++ anyway  and I can’t imagine they would have an intel compiler but not g++.

**Comment by Expander** [comment]
Many thanks for the good news!

@pathron, @iolojz, @wkotlarski, @azedarach would you be ok with merging this branch into development?

**Comment by azedarach** [comment]
I would be OK with merging this now

**Comment by wkotlarski** [comment]
I'm also OK with merging this.

**Pull request merged**
