### PR TITLE
Feature: add getters for lepton pole/running masses

### PR DESCRIPTION
**Pull request by Expander**
to make the generated code more compact

### CODE REVIEW

**Comment by Expander** [comment]
Note: The test `test/test_MRSSM2_gmm2.x` does fail, but it failed even before this PR.

**Comment by Expander** [comment]
One remark: In the meta code I see the following comment:
~~~.m
(* Dominik suggest that the phase space prefactor should use pole masses  so we get them from the input file *)
~~~
Below the comment, however, the running lepton masses (not the pole masses) are used.

**Comment by Expander** [comment]
I think this PR is ready to be merged.

However, we should discuss if we should actually use the lepton pole masses in the l -> l+gamma calculation, as suggested by Dominik.

**Review by wkotlarski — APPROVED** [review]
> One remark: In the meta code I see the following comment:
> 
> ```
> (* Dominik suggest that the phase space prefactor should use pole masses  so we get them from the input file *)
> ```
> 
> Below the comment, however, the running lepton masses (not the pole masses) are used.

I think it might be typo. Me or someone else could think that `qedqcd.displayMass` returns an OS mass. I'll discuss it with @uukhas in another PR.

**Pull request merged**
