### PR TITLE
Feature: move testing models to test/model_files/

### PR DESCRIPTION
**Pull request by Expander**
This PR moves several "testing" models to the `test/model_files/` directory. This cleans up the `model_files/` directory.

### CODE REVIEW

**Comment by Expander** [comment]
fixes #460

**Review by wkotlarski — COMMENTED** [review]
Should `CMSSMMediumPrecision` really be in the `THDMIIMSSMBC` subdirectory?

**Comment by Expander** [comment]
> Should `CMSSMMediumPrecision` really be in the `THDMIIMSSMBC` subdirectory?

Ouch! Thanks for spotting this, this was a mistake, which I have corrected.

**Review by wkotlarski — APPROVED** [review]

**Comment by Expander** [comment]
@pathron : Would you mind looking into the directory:
https://github.com/FlexibleSUSY/FlexibleSUSY/tree/feature-test-models/model_files
to check if you're ok with this selection of models to be used by users?

**Pull request merged**
