### PR TITLE
Improve mssm_twoloop_as.cpp compile time

### PR DESCRIPTION
**Pull request by Expander**
by shrinking the expressions by a factor 10.

@wkotlarski Would you mind checking how long it now takes on your machine to compile? (You said the old version did take several *hours* to compile.)

### CODE REVIEW

**Comment by wkotlarski** [comment]
Much better
```
make  3115,95s user 37,25s system 88% cpu 59:37,18 total
```
Now the longest one is this
```
Building model_specific/MSSM_thresholds/mssm_twoloop_mtau.o
```
and then those ones
```
Building model_specific/MSSM_thresholds/mssm_twoloop_mb.o
Building model_specific/MSSM_thresholds/mssm_twoloop_mt.o
```

**Comment by Expander** [comment]
Ok, thanks for testing! I've now reduced `mssm_twoloop_mb.cpp` and will look at `mssm_twoloop_mtau.cpp` next.

Btw., I'm a bit surprised why the compilation takes so long on your machine. Which compiler are you using? How much memory and which CPU do you have? (I'm asking just out of curiosity to know where such problems can be expected.)

**Comment by wkotlarski** [comment]
```
clang version 10.0.0 
Processors: 4 × Intel® Core™ i5-7600 CPU @ 3.50GHz
Memory: 31,3 GiB
```

**Comment by Expander** [comment]
Interesting! That's actually a decent machine. I'm using clang 11.0.0 on a i7-5600U CPU @ 2.60GHz 11 GiB RAM. On my machine the original compilation time was below 1 min.

**Comment by pathron** [comment]
On my machine the master was already fast with clang-6.0, under a minute using -j12 on a machine with Intel® Core™ i7-9850H CPU @ 2.60GHz × 12 and 32 gigs memory,  and it doesn't change much on this new branch.

Would be nice to understand these very different compile times,  At some point FS was taking a long time to compile inside gambit for some people (using oldish g++ compilers) and i was completely unaware of the problem, as it compiled very fast for me with newer g++.

**Comment by wkotlarski** [comment]
@Expander, `clang 11.0.0` is a development version, right? Official one is `10`. @pathron version `6` is fine. `7` too because the tests run on this one. So something happened in `8` or `9`.

**Comment by Expander** [comment]
Thanks for the feedback.

I know that one can install clang 8 and 9 using llvm's official package repository for Debian (and maybe also Ubuntu):
~~~
deb http://apt.llvm.org/buster/ llvm-toolchain-buster-9 main
deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster-9 main
~~~
I'm using the latest one from here:
~~~
deb http://apt.llvm.org/buster/ llvm-toolchain-buster main
deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster main
~~~

**Comment by Expander** [comment]
@wkotlarski I've now reduced the size of `mssm_twoloop_mtau.cpp`, too. Would you mind having a look at the compile times now?

**Comment by wkotlarski** [comment]
With pre-generated vertices
```
make  688,46s user 26,98s system 91% cpu 13:01,78 total
```
I'd say now it's fine.

**Comment by Expander** [comment]
Thanks for testing! (It is also faster now. :) )

**Pull request merged**
