### PR TITLE
Always enable GM2Calc module

### PR DESCRIPTION
**Pull request by Expander**
This fixes the following issues:

* Removes a circular dependency between GM2Calc and FlexibleSUSY

* Simplifies configuration of models that use `aMuonGM2Calc` (no need to pass `--with-optional-modules=GM2Calc`)

* GM2Calc is not re-build after each call of `./configure` (improves compile time)

* Removes GM2Calc from the (not frequently used) status of being an addon (which it no longer is, as it is completely independent now since version 1.6.0)

Disadvantages:

* GM2Calc must be build once

* Each spectrum generator is linked against `libGM2Calc`

### CODE REVIEW

**Comment by wkotlarski** [comment]
So in short:: `GM2calc` is now distributed with `FlexibleSUSY`?

**Comment by pathron** [comment]
I can’t look at code til tomorrow, but why is it necessary to always link the spectrum generators to libGM2Calc?  That’s a bit weird since most spectrum generators will not be MSSM.  Or do I misunderstand... ah maybe you just mean that now if one want to use it with any FS spectrum generator then that particular one needs to be linked with it?

**Comment by Expander** [comment]
> So in short:: `GM2calc` is now distributed with `FlexibleSUSY`?

Yes, but it has always been distributed along with FS. However, before this PR, it had to be activated "by hand" to make it work. With this PR the "by hand" activation is no longer necessary.

**Comment by Expander** [comment]
> I can’t look at code til tomorrow, but why is it necessary to always link the spectrum generators to libGM2Calc? That’s a bit weird since most spectrum generators will not be MSSM. Or do I misunderstand... ah maybe you just mean that now if one want to use it with any FS spectrum generator then that particular one needs to be linked with it?

You are right, this is not optimal. I can change this, so that it is linked only if needed.

**Comment by wkotlarski** [comment]
What is the relation between this `GM2Calc` and [this](https://github.com/GM2Calc/GM2Calc)?

**Comment by Expander** [comment]
> What is the relation between this `GM2Calc` and [this](https://github.com/GM2Calc/GM2Calc)?

They are identical. I.e. GM2Calc is shipped with FS.

In principle one could make it a third-party dependency (as TSIL, Himalaya or LoopTools). However, it is very small (compared to the other dependencies) and so we had distributed it in the past along with FS. (And fewer dependencies is in general better for portability.)

BTW, GM2Calc actually started as a FS addon and evolved to a stand-alone code. :)

**Comment by wkotlarski** [comment]
In principle I don't have problem with any of this. I was just thinking that we're now maintain two identical codes in 2 places with different build systems. Could we use git's submodules?

**Comment by Expander** [comment]
> In principle I don't have problem with any of this. I was just thinking that we're now maintain two identical codes in 2 places with different build systems. Could we use git's submodules?

That's an interesting idea. However, if we'd use a submodule for GM2Calc, then suddenly FS becomes dependent on CMake (which is used in GM2Calc). Also, it is not so clear to me how we would ship FS with a specific GM2Calc version then.

**Comment by wkotlarski** [comment]
There was a time when we wanted to move to CMake. If that's still an option, we could start with adding CMake as dependency.

**Comment by Expander** [comment]
> There was a time when we wanted to move to CMake. If that's still an option, we could start with adding CMake as dependency.

I'm still thinking about this and played around with some setups, but I'm afraid this will not come soon. There are some problems with moving to CMake that have to do with our code generation (in particular generating files whose names are not known a priori).

**Comment by Expander** [comment]
After thinking a bit about your concerns, @pathron and @wkotlarski , it may be best to make GM2Calc a third-party dependency, that we install via `conan`. In this way it is enabled only if needed and we don't need to maintain it. What do you think?

**Pull request closed without merging**
