### PR TITLE
test against intel compiler

### PR DESCRIPTION
**Pull request by wkotlarski**
Intel compilers are now free. This PR adds tests against them. I'm still analysing the output. One thing I've seen is that I'm not sure if icpc version is determined correctly
```
Checking for C++ compiler icpc ... found /opt/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/icpc
Checking for type of C++ compiler icpc ... Intel
Checking for icpc compiler version >= 17.0.0 ... ok (version 20.2.1)
```
I think it should be `2021.2.0`, not `20.2.1`.

### CODE REVIEW

**Comment by Expander** [comment]
Very nice, thanks!

> I think it should be `2021.2.0`, not `20.2.1`.

Oh, did they change the version numbering scheme?
Then the determined version is not correct.

**Review by Expander — APPROVED** [review]

**Comment by wkotlarski** [comment]
With intel `test_MSSM_2L_analytic.m` fails. [Here](https://github.com/FlexibleSUSY/FlexibleSUSY/suites/3053821295/artifacts/69480874) logs.

**Comment by Expander** [comment]
The problem is:
~~~
CreateExecutable::cmperr: 
   Compile error: collect2: error: ld returned 1 exit status
Error: cannot create executable
~~~
Mathematica fails to compile the test-code with the intel compiler.

**Comment by wkotlarski** [comment]
Thanks, that was helpful :smile: The problem is in `test_MSSM_2L_analytic.m`, when you `CreateExecutable` you link agains `gfortran`. If FS was compiled with `ifort` you should link agains `imf`. Then the test passes.

**Comment by Expander** [comment]
Ah, yes! :)

**Comment by wkotlarski** [comment]
Is there a way to set this based on the configure options?

**Comment by Expander** [comment]
Yes, that would be best actually.
The `configure` script may simply generate a `.m` file that contains the libraries to be linked. What do you think?

**Comment by wkotlarski** [comment]
Sounds good. Are there other tests, apart from `test_MSSM_2L_analytic`, that require this information?

**Comment by Expander** [comment]
No, `test/test_MSSM_2L_analytic.m` seems to be the only test.

**Comment by wkotlarski** [comment]
@Expander, will you make this change or should I do it?

**Comment by Expander** [comment]
If you have the time, can you please do it?

**Comment by wkotlarski** [comment]
Done. But it's the end of the month, meaning that all tests are again failing with
```
./createmodel: line 235:  1026 Aborted                 (core dumped) "${mathematica_kernel}"  > /dev/null 2>> ${createmodel_log}
```
so I'll have to wait few days before I can run those tests.

**Comment by Expander** [comment]
> Done. But it's the end of the month, meaning that all tests are again failing

What a fun!

**Comment by wkotlarski** [comment]
On my machine there's one more test that fails
```diff
running: icpc -MM -MP test/depgen/subdir/base.cpp    
running: test/../config/depgen.x -MM -MP test/depgen/subdir/base.cpp    
Error: files are not equal test/test_depgen.out.1 and test/test_depgen.out.2    
Difference:    
--- test/test_depgen.out.1 2021-06-28 12:51:50.343158116 +0200    
+++ test/test_depgen.out.2 2021-06-28 12:51:50.343158116 +0200    
@@ -1,5 +1,3 @@    
  b a s e . o : t e s t / d e p g e n / s u b d i r / b a s e . c p p t e s t / d e p g e n / s u b d i r / b a s e . h p p     
      
- / u s r / i n c l u d e / s t d c - p r e d e f . h :     
-     
  t e s t / d e p g e n / s u b d i r / b a s e . h p p :     
Test result: FAIL    
```

**Comment by Expander** [comment]
Ok, seems like a bug, because a system header should not be included.
But why are there spaces between the characters in the file names?

**Comment by Expander** [comment]
Sorry, the spaces are ok. They come from the testing code. :)

**Comment by Expander** [comment]
Could you please paste the output of the following command?
~~~
icpc -MM -MP test/depgen/subdir/base.cpp
~~~

**Comment by wkotlarski** [comment]
```
base.o: test/depgen/subdir/base.cpp test/depgen/subdir/base.hpp

/usr/include/stdc-predef.h:

test/depgen/subdir/base.hpp:
```

**Comment by Expander** [comment]
Ok, so `icpc` adds the extra line `/usr/include/stdc-predef.h:`, although there is no such explicit header dependency.

**Comment by Expander** [comment]
A simple fix would be to simply remove all lines that contain patterns of the form `^/.*`. I.e. we would ignore such cases. What do you think?

**Comment by wkotlarski** [comment]
Before I comment could you tell me what does this test check exactly?

**Comment by Expander** [comment]
This particular test checks that the `-MM -MP` flags are simultaneously supported.
The `-MP` option (in gcc and clang) add a phony target for each dependency (except the main file).

**Comment by wkotlarski** [comment]
> A simple fix would be to simply remove all lines that contain patterns of the form `^/.*`. I.e. we would ignore such cases. What do you think?

I don't know enough to have strong opinion. Your solution seems reasonable.

**Comment by Expander** [comment]
Could you please try the following patch?
~~~.patch
diff --git a/test/test_depgen.sh b/test/test_depgen.sh
index 8b780036e..e48fd7bd6 100755
--- a/test/test_depgen.sh
+++ b/test/test_depgen.sh
@@ -25,8 +25,8 @@ run_depgens() {
 
     rm -f ${OUTPUT}.1 ${OUTPUT}.2
 
-    $cmd1 $file | awk "${awk_join_lines}" | sed 's/ */ /g' > ${OUTPUT}.1
-    $cmd2 $file | awk "${awk_join_lines}" | sed 's/ */ /g' > ${OUTPUT}.2
+    $cmd1 $file | awk "${awk_join_lines}" | sed 's/ */ /g' | sed '/^\/.*/d' | sed '$!N; /^\(.*\)\n\1$/!P; D' > ${OUTPUT}.1
+    $cmd2 $file | awk "${awk_join_lines}" | sed 's/ */ /g' | sed '/^\/.*/d' | sed '$!N; /^\(.*\)\n\1$/!P; D' > ${OUTPUT}.2
 
     diff=$(diff -u ${OUTPUT}.1 ${OUTPUT}.2)
 
~~~

**Comment by wkotlarski** [comment]
Nope. It seems it didn't remove this line.

**Comment by wkotlarski** [comment]
One more. `test_array_view` fails with
```
test/test_array_view.x: error while loading shared libraries: libifcore.so.5: cannot open shared object file: No such file or directory
```

**Comment by Expander** [comment]
ok, 2nd try:
~~~.patch
diff --git a/test/test_depgen.sh b/test/test_depgen.sh
index 8b780036e..1d112acfa 100755
--- a/test/test_depgen.sh
+++ b/test/test_depgen.sh
@@ -25,8 +25,8 @@ run_depgens() {
 
     rm -f ${OUTPUT}.1 ${OUTPUT}.2
 
-    $cmd1 $file | awk "${awk_join_lines}" | sed 's/ */ /g' > ${OUTPUT}.1
-    $cmd2 $file | awk "${awk_join_lines}" | sed 's/ */ /g' > ${OUTPUT}.2
+    $cmd1 $file | awk "${awk_join_lines}" | sed '/^\/.*/d' | sed '$!N; /^\(.*\)\n\1$/!P; D' | sed 's/ */ /g' > ${OUTPUT}.1
+    $cmd2 $file | awk "${awk_join_lines}" | sed '/^\/.*/d' | sed '$!N; /^\(.*\)\n\1$/!P; D' | sed 's/ */ /g' > ${OUTPUT}.2
 
     diff=$(diff -u ${OUTPUT}.1 ${OUTPUT}.2)
 
~~~

**Comment by wkotlarski** [comment]
There's a problem with `test/test_CMSSM_librarylink_slha.sh`. With Collier, there's a large difference in H->VV channel (the one we integrate numerically). For all other channels relative differences are at the e-9 - e-10 level. For H->VV it's e-3. On the other hand, with LoopTools there's a problem with signs in the mixing matrices (the signs are unphysical).

**Comment by wkotlarski** [comment]
Hi @Expander, do you have any thoughts about this problem?

**Comment by Expander** [comment]
Sorry for the delay.
* I think we'd need to check what's going on in the H ->VV channel. The others seem fine.
* Regarding the mixing matrices: Since the sign is unphysical, I think the test must be fixed.

**Comment by wkotlarski** [comment]
This is the finite precision of numeric integration. If I increase the precision then the test passes. This is specific to intel as other compilers are more deterministic (the same number both from normal and matlink run).

**Comment by Expander** [comment]
Which numeric integration and precision are you referring to?

**Comment by wkotlarski** [comment]
H -> V*V* is integrated numerically with number of evaluations giving roughly a 1e-3 - 1e-4 precision. On intel there are fluctuations from run to run below this precision while on gcc/clang the result is stable.

**Comment by Expander** [comment]
I find this a bit strange, because the integration routine comes from GSL, which I think is quite stable. Or do you know if the issue originates from the formulation of the integrand on the FS side?

**Comment by wkotlarski** [comment]
H -> V*V* with icpc
(1M calls): 0.2543 vs 0.2544 GeV
(4B calls): 0.25437630499802424 vs 0.25437645149361317 GeV

**Comment by Expander** [comment]
Ok, maybe we can be pragmatic. What would you say is the theory uncertainty of these values?
If the theory uncertainty >> the numerical precision, we may allow for a larger numerical deviation.
What do you think?

**Comment by wkotlarski** [comment]
The problem is that precision is global. Lowering it would also lower precision of comparison for mass spectra, which we probably don't want.

**Comment by Expander** [comment]
I see. Can we "split" the precision that we use for the check, so that we compare the decays with a lower precision?

**Comment by wkotlarski** [comment]
We'd have to split the ouput files in half. Some of your bash magic would be in order.

**Comment by Expander** [comment]
Is the issue only the file `test_CMSSM_librarylink_slha.sh`? (I.e. only the CMSSM is affected, including decays.)

**Comment by wkotlarski** [comment]
I think so.

**Comment by Expander** [comment]
Sorry, I have a question regarding the test `test_CMSSM_librarylink_slha.sh`: This test compares the Mathematica interface against the command-line interface. Both interfaces are compared based on the SLHA output file. I don't see a reason why this test should fail. Both output files should be produced by the same internal code and thus should give identical output. Or am I looking into the wrong test?

**Comment by wkotlarski** [comment]
We're doing monte carlo integration which is not deterministic.

**Comment by Expander** [comment]
Are you saying that true random numbers (not pseudo random numbers) are used, so different runs of FS really produce different results in some digits?

**Comment by wkotlarski** [comment]
Yes. It's this
```cpp
const gsl_rng_type *T = gsl_rng_default;
gsl_rng *r = gsl_rng_alloc (T);
```

**Comment by Expander** [comment]
Sorry to be pedantic, I've just looked into the GSL documentation:

_If you don’t specify a generator for `GSL_RNG_TYPE` then `gsl_rng_mt19937` is used as the default. The initial value of `gsl_rng_default_seed` is zero._

When I compile the following program that uses the rng used in FS:
~~~.cpp
#include <stdio.h>
#include <gsl/gsl_rng.h>

gsl_rng * r;  /* global generator */

int main()
{
  const gsl_rng_type * T;

  // gsl_rng_env_setup();

  T = gsl_rng_default;
  r = gsl_rng_alloc (T);

  printf ("generator type: %s\n", gsl_rng_name (r));
  printf ("seed = %lu\n", gsl_rng_default_seed);
  printf ("first value = %lu\n", gsl_rng_get (r));

  gsl_rng_free (r);
  return 0;
}
~~~
I get the following output:
~~~.bash
generator type: mt19937
seed = 0
first value = 4293858116
~~~
I.e. the generator is Mersenne Twister pseudo-random generator. According to the documentation, this rng does not give "genuine" random values. Instead it creates uncorrelated (reproducible) pseudo-random numbers.

If all of this is true, then there should be no difference between two FS runs with identical input. Could it be that the issue is more subtle?

**Comment by wkotlarski** [comment]
I think I've solved previous problems. Any idea what to with this [test_pv_crosschecks.sh.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/7014465/test_pv_crosschecks.sh.log)?

**Comment by Expander** [comment]
> I think I've solved previous problems. Any idea what to with this [test_pv_crosschecks.sh.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/7014465/test_pv_crosschecks.sh.log)?

Ouch, there seem to be genuine problems:
~~~
FlexibleUpstream/test/test_pv_crosschecks.cpp(215): error: in "looptools_check_points": difference{2} between a{-10.241354676386212} and b{10.241354676386212} exceeds 4.0000000000000002e-09
~~~
This seems like a bug in some loop library, that could lead to actual differences in our output. But I'm not sure if the bug is in FFLite or LoopTools. Do you know?

**Comment by wkotlarski** [comment]
```
LesHouches input.----------------
##264     #:3   <== 4.56949945E-03
##264     #:3   ==> -4.56949945E-03
@ Absolute error = 9.1389989000e-3, Relative error = 2.0000000000e+0
----------------
##267     #:3   <== 9.99989560E-01
##267     #:3   ==> -9.99989560E-01
@ Absolute error = 1.9999791200e+0, Relative error = 2.0000000000e+0
----------------
##320     #:3   <== -9.89861016E-01
##320     #:3   ==> 9.89861016E-01
@ Absolute error = 1.9797220320e+0, Relative error = 2.0000000000e+0
----------------
##323     #:3   <== 1.42039321E-01
##323     #:3   ==> -1.42039321E-01
@ Absolute error = 2.8407864200e-1, Relative error = 2.0000000000e+0

+++  File "test/test_CMSSM_librarylink_slha.out1.spc" differs from file "test/test_CMSSM_librarylink_slha.out2.spc"
Test result: FAIL
```

**Comment by Expander** [comment]
Sorry, I'm procrastinating on this issue, because performing matrix algebra in a shell script is a pain and I don't know just now how to properly handle this. Do you have an idea?

**Comment by wkotlarski** [comment]
Hi @Expander. The `icpc` compiler will be removed from intel mid 2023. They are moving to llvm backend. I only broadly know which part of the compiler does what, so I don't know if it still makes sense to try to run tests with intel as clang is also based on llvm.

**Pull request closed without merging**
