### PR TITLE
Fix `shellcheck` warnings

### PR DESCRIPTION
**Pull request by uukhas**
I will be modifying the following set by adding new items as soon as I finish them.
- [x] SC2155: Declare and assign separately to avoid masking return values. 729b8ec
- [x] SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails. 435a644
- [x] SC2154: ___ is referenced but not assigned. ac88399, 3c5d434
- [x] SC2046: Quote this to prevent word splitting. 7fd5449
- [x] SC2166: Prefer [ p ] || [ q ] as [ p -o q ] is not well defined. d5b49c1
- [x] SC2034: ___ appears unused. Verify use (or export if used externally). 98d7528
- [x] SC2115: Use \"${var:?}\" to ensure this never expands to / . 6fb2e3e
- [x] SC1090: Can't follow non-constant source. Use a directive to specify location. 997d508
- [x] SC2065: This is interpreted as a shell file redirection, not a comparison. fabb125
- [x] SC2039: In POSIX sh, 'local' is undefined. "Fixed" in 0c271c2

### CODE REVIEW

**Comment by uukhas** [comment]
@Expander, there are only 2 problems now:
1) SC2065: in the file `utils/scan-slha.sh` there is a line, which I cannot understand:
   ```bash
   test -z "$value" > /dev/null
   ```
   **Q:** What is it suppose to do?
2) SC2039: `shellcheck` says, that `local` does not exist for POSIX `sh`.
   **Q:** What are we going to do with that?

Once we fix them, I would suggest to check both errors and warnings in the actions.

**Comment by wkotlarski** [comment]
> Once we fix them, I would suggest to check both errors and warnings in the actions.

Before the merge please replace `error` with `warning` in CI script.

**Comment by Expander** [comment]
>     1. SC2065: in the file `utils/scan-slha.sh` there is a line, which I cannot understand:
>        ```shell
>        test -z "$value" > /dev/null
>        ```
>        **Q:** What is it suppose to do?

This command is supposed to work in combination with the one that follows:
~~~.sh
# check if entry exists
# if entry exists, set value=1, otherwise set value=0
test -z "$value" > /dev/null
value=$?
~~~
Here `value` stores the exit code of the previous command, which checks whether `value` is empty or not.

**Comment by uukhas** [comment]
Why `> /dev/null` is used?
Is it equivalent to 
```bash
[ -z "$value" ]
```
?

**Comment by Expander** [comment]
> Why `> /dev/null` is used? Is it equivalent to
> 
> ```shell
> [ -z "$value" ]
> ```
> 
> ?

Yes, it is a more complicated variant of `[ -z "$value" ]`. So, we may simply use the latter. :)

**Comment by uukhas** [comment]
It seems that a lot of shells support a `local` command, like in [the](https://itectec.com/unixlinux/shell-list-of-shells-that-support-local-keyword-for-defining-local-variables/) post.
I suggest to add an appropriate directive to the `shellcheck` to ignore this warning.

**Comment by Expander** [comment]
>  I suggest to add an appropriate directive to the `shellcheck` to ignore this warning.

I think that's a good option for now.

**Review by wkotlarski — APPROVED** [review]
I'm not competent enough to comment. I'm trusting you.

**Comment by uukhas** [comment]
@wkotlarski, I have changed the action in 0c271c2 to increase the level of serenity to `warning`. 

It is OK to put `echo` in the `.yaml` configuration, as I did?

**Comment by wkotlarski** [comment]
It doesn't hurt. If you want it that way I'm ok with it.

**Comment by uukhas** [comment]
@Expander, everything seems to work. 

Unfortunately, I have created this PR from my branch. I would like to copy this branch to `FlexibleSUSY` first in order to check, whether everything works from the side of github actions. It will save the whole history of the changes, but will require new PR. 

It is OK to proceed in this way?

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
Yes, please proceed.

**Pull request merged**
