### PR TITLE
Is<particle_type> cross checks and caching

### PR DESCRIPTION
**Pull request by uukhas**
* Improve the speed for multiple calls thanks to caching.
* Print a warning if unexpected input is parsed.

### CODE REVIEW

**Comment by wkotlarski** [comment]
I have 2 questions:

1. Do those functions actually use so much time that this complication is justified.
2. Why not just make functions remember computed values (see [here](https://reference.wolfram.com/language/workflow/WriteAFunctionThatRemembersComputedValues.html))?

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
I'm also wondering how much time is saved.

**Comment by uukhas** [comment]
Let me start from this question:
>     2. And if yes, why not just make functions remember computed values (see [here](https://reference.wolfram.com/language/workflow/WriteAFunctionThatRemembersComputedValues.html))?
I am using exactly this mechanism, but for `cache$***` function:
```mathematica
Module[{cache},
   IsFermion[SARAH`bar[sym_]] := cache[sym];
   IsFermion[sym_] := cache[sym];
   cache[sym_] := cache[sym] = IsOfType[sym, F];
];
IsFermion[sym_List] := And @@ (IsFermion /@ sym);
IsFermion // Utils`MakeUnknownInputDefinition;
IsFermion // Protected;
```
Why? Because of the line `IsFermion // Protected;`, which forbids me to do it via "normal" `IsFermion[bar[sym_]] := IsFermion[bar@sym] = <...>`. 

Why `Protected`? Because I would like to prevent some unexpected re-definitions somewhere in the other parts of the code.

Also, in order to prevent ill-defined usage I use ``IsFermion // Utils`MakeUnknownInputDefinition;`` as well.

**Comment by uukhas** [comment]
>     1. Do those functions actually use so much time that this complication is justified?
**So much time**? - for `SM` and `MSSM` not really (typically ~20%):
```mathematica
IsScalar@bar@hh; (* Call with message: first call 2e-2s, the next ones 1e-5s *)
IsScalar@hh; (* Call without message: first call 5e-6s, the next ones ~4e-6s *)
```

**Comment by wkotlarski** [comment]
Can you show any measurable difference in runtime for the user?

**Comment by uukhas** [comment]
@wkotlarski, for `SM`:
|| old  | new | boost|
| --- | --- | --- | --- |
| real | 1m 17.515s  | 1m 17.**166**s  | **0.5**% |
| user | 2m 5**2.974**s  | 2m 53.538s  | -0.2% |
| sys | 8.438s  | 8.**312**s  | **1.5**% |

The code does not make the calculation slower or faster at this point. What it does is:
a) Some *almost* free physical checks
b) Speed up in future, if `Is<...>` functions are used more often

**Comment by wkotlarski** [comment]
My point is that we're introducing a lot of conceptual complications for no gain. Before it was obvious what those functions were doing. Now it is not. I'm sorry, but I fail to see benefits in this change.

**Comment by uukhas** [comment]
Benefit is that if there is a `bar@VP`, for example, somewhere in the code, then `FlexibleSUSY` can at least warn the user, that something might go wrong. Also, it is still obvious what the function is doing, because of its name.

**Comment by uukhas** [comment]
You use, for example, `std::cout` because you have a simple name and a description. You do not care, how the actual realization of the function is done.

**Comment by uukhas** [comment]
The point is that I did not change the interface of this function, but I added some nice physics-program-specific checks with no loss of the speed and with some benefits in scaling. Why should this improvement be discarded?

**Comment by wkotlarski** [comment]
You're talking from the point of view of a user. But someone will come after you and will have to maintain it. I'm sorry, but my opinion is that the caching is an unneeded complication. But it is @Expander that decides what too do. I just voiced my opinion :heart:

**Comment by uukhas** [comment]
But this is an improvement in maintenance!

a) Someone can create a weird ``SARAH` `` file. We do not want do know, how this external package works. But what we know, is that we do not want `bar@VP` or  `bar@hh`, or `conj@Fe` in the code, because it is not intuitive. So, we check indirectly some inputs.

b) Someone in the future would be creating some ``FlexibleSUSY` `` code. And this person would like to create something like `bar@VP` by wish or by accident. And my improvement has a chance to warn about this, is `Is<...>` is called.

c) Now, if someone calls `IsVector[SOMEHEAD[Vp, Fe, gG]]`, then the code is just not evaluated, nothing more. It is not working if `SOMEHEAD` is not `List`. And this might lead to a many-hours debugging. Because of ``Utils`MakeUnknowInputDefinitions`` our `FlexibleSUSY` will immediately stop and warn the user about this issue.

d) `IsScalar` - is a very nice name! Short and self descriptive. This is why someone will definitely create the same function in the future a well. And, because of default behavior of `Mathematica` for contexts, this new definition will be added or even override some existing ones in `TreeMasses`. Now, it is not possible, because symbols are `Protected`.

4 benefits for free.

**Comment by wkotlarski** [comment]
BTW, there's something that came to my mind. If it's about solving the problem with `conj` not a scalar etc, wouldn't it be better to move it to some other place? Because in principle we'd now had to do the same for every other function that might take a field wrapped in a head. Wouldn't it make more sense to make a rule that `conj` and `bar` check their arguments automatically?

**Comment by uukhas** [comment]
@wkotlarski, yes. I absolutely agree. Where should we do this instead? For `VVVV` vertices it was possible to make a wrapper in the PR relevant for #271. Here, it might be a bit different, because It seems that `bar` and `conj` are already really strongly specialized, so that it is hard for me to imagine, how to do this. There might be better to create a separate, orthogonal. Checker, maybe in the `Wrappers`.

**Comment by uukhas** [comment]
@wkotlarski, you are probably right after all.

This improvement shall be done only when it is required. So far there were no reports about the problem, which I tried to solve.

**Pull request closed without merging**
