### PR TITLE
Check for an equality of timestamps.

### PR DESCRIPTION
**Pull request by uukhas**
A fix for #370.

### CODE REVIEW

**Comment by Expander** [comment]
Many thanks for the patch! Can you please briefly explain the strategy that you follow with this patch to fix the issue?

**Comment by uukhas** [comment]
Before the logic was: if `FlexibleSUSY.m` was **changed**, then we need to update `module.mk`.
By **changed** it was meant, that `FlexibleSUSY.m` becomes **newer** then `module.mk`.

In the issue #370, I have found an unobvious way, how to "change" `FlexibleSUSY.m` and make it **older**, then `module.mk`.
In order to solve this problem, we can check timestamps of `FlexibleSUSY.m` and `module.mk`:
```
are the same => we do not need to update model specific modules
are not the same => we need to 1) make some changes, 2) make timestamps the same
```

**Comment by Expander** [comment]
Many thanks for the explanation!

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
Please feel free to merge the PR.

**Pull request merged**
