### PR TITLE
Fix CXXDiagrams`FeynmanDiagramsOfType[] complex-conjugation issue

### PR DESCRIPTION
**Pull request by iolojz**
This should fix bug https://github.com/FlexibleSUSY/FlexibleSUSY/issues/69.
@wkotlarski Can you confirm this?
@Expander I have tested that amuon returns the same values as before in the SM and MSSM. I could do the same for edm in MSSMCPV next week. @wkotlarski If you need this fix earlier, you need to check it yourself.

### CODE REVIEW

**Comment by wkotlarski** [comment]
In the MRSSM I have a diagram contributing to &mu;&rarr;e&gamma; with H&#x207A; and neutrino in the loop. How does your routine determines the position of scalar is in the generated vertices? Should we have a template specialization that makes sure that if we don't have (but it's needed) a `barFFS` vertex in the file, the code will call `barFSF` or `SbarFF` vertices (and vice versa)?

**Comment by SoundSonic1** [comment]
Seeing all these sign changes in your commits, what is the convention of `FermionVertex` and `PhotonEmitter::electric_charge` now?

**Comment by iolojz** [comment]
I feel like I have answered those questions at least ten times already. Please read the documentation from the above commit and see if it answers your questions. Otherwise, we will have to talk about this again.

**Comment by wkotlarski** [comment]
Was it an answer to @SoundSonic1 or me?

**Comment by iolojz** [comment]
Both. @wkotlarski There will only ever be one order of fields, if you properly select for inserted fermions, scalars etc. @SoundSonic1 by noticing the rules for contracted fields: `EDMField` is an incoming external field that gets contracted with the first field in vertex number four. Thus the first entry of vertex number four is simply `EDMField`. Likewise, the first entry of vertex number five is `EDMField*` and the first entry of vertex number six is `Photon`. Now, we define `PhotonEmitter` to be the third entry of vertex number four, because we know it gets contracted with the second entry of vertex number six - i.e the second entry of the photon vertex. We also define the `ExchangeParticle` to be the second entry of vertex number four which we know gets contracted with the second entry of vertex number five.
Furthermore, we assert that the photon vertex is of the form (meta/EDM.m:136)
`{Photon,PhotonEmitter*,PhotonEmitter}`
which implies that a resulting diagram looks like
`{EDMField, EDMField*, Photon, {EDMField, ExchangeParticle, PhotonEmitter}, {EDMField*, ExchangeParticle*, PhotonEmitter*}, {Photon, PhotonEmitter*, PhotonEmitter}}`
Thus, the vertices one gets are:
`{{EDMField, ExchangeParticle, PhotonEmitter}, {EDMField, ExchangeParticle*, PhotonEmitter*}, {Photon, PhotonEmitter*, PhotonEmitter}}`
Admittedly, these are not the standard vertices one would write down, but one could modify the adjacency matrix to have the fields be ordered more naturally.
`EDMField` is specified by the user, but we can consider the case of a lepton: `Fe` in the MSSM. The charge we need to evaluate the diagram, is the charge flowing from vertex four to vertex 6. Thus, in the SARAH convention where 'everything is incoming', the charge flowing away from vertex four along the `PhotonEmitter` line is `-PhotonEmitter::electric_charge`.

This reflects the difference introduced by this patch. Prevously we had vertex four represented by {EDMField*, ExchangeParticle, PhotonEmitter}
and thus correspond to an 'everything is outgoing' convention.

**Comment by wkotlarski** [comment]
Using the graphs
```
{{0,0,0,1,0,0},
{0,0,0,0,1,0},
{0,0,0,0,0,1},
{1,0,0,0,1,1},
{0,1,0,1,0,1},
{0,0,1,1,1,0}}
```
for external fields `{1 -> Fe, 2 -> bar[Fe], 3 -> VP}` we get from `FeynmanDiagramsOfType`, for example, vertices `{bar[Fe], Ah, Fe}, {Fe, Ah, bar[Fe]}, {VP, bar[Fe], Fe}`. According to Markus, 
```
Vertex[{Fe, Ah, bar[Fe]}][L,R] = - Vertex[{bar[Fe], Ah, Fe}][R,L]
```
So one has to rewrite internal formulas in terms of this other vertex. I need to convince myself that this is a proper solution.

**Comment by iolojz** [comment]
Well, why don't you simply use the second vertex in place of the first one,
if you can choose?
Why do you not represent the topology using a different adjacency matrix,
if you want the fields to appear in a different order?

With regard to `PL`/`PR`: yes, that was figured out by Jae-Hyeon and you
can get that by using `SortCp[]`.

One more thing though... An automatized algorithm cannot guess in which
order your favourite paper has defined its vertices (is the boson
sandwiched, what is the momentum flow, etc.)

**Comment by wkotlarski** [comment]
So just for our understanding: so is the order of fields returned by InsFields meaningles? It only provides information about the particles that should be inserted, but not if one inserts them normally or conjugated and how are vertices oriented?

**Comment by iolojz** [comment]
It seems to me, you got ```SARAH`InsFields[]``` wrong. What one does is feeding it something of the form
```
{
{
C[Fe, FieldToInsert[1], FieldToInsert[2]],
C[AntiField[FieldToInsert[1]], bar[Fe], FieldToInsert[3]],
C[VP, AntiField[FieldToInsert[2]], AntiField[FieldToInsert[3]]]
},
{
FieldToInsert[1], FieldToInsert[2], FieldToInsert[3]
}
}
```
Then, it will figure out all possible insertion of fields where none of the `C[]`s (vertices) would evaluate to zero as would be determined by ```SARAH`Vertex[]```. Also, the second list fed to ```SARAH`InsFields[]``` is not necessary, but very convenient because it enables the user to easily parse which fields were inserted. In fact, without supplying it, getting the inserted fields would be rather tricky as `C` has the attribute `Orderless`. Hence, the order of the fields in the `C[]`s is not even preserved by ```SARAH`InsFields[]```.

Of course, the initial (and thus final) ordering of the fields in the vertices is __not__ random, but rather figured out automatically from the given adjacency matrix along with the external fields passed to ```CXXDiagrams`FeynmanDiagramsOfType[]``` - the information is only temporarily lost when applying `C[]` before sending everything to ```SARAH`InsFields[]```. That is why you can influence the order by choosing a different adjacency matrix to represent your topology of interest - that is equivalent to a permutation of the indices of the vertices.

**Comment by wkotlarski** [comment]
I never said that the order **is** random. I know it's deterministic. What I mean is that it's meaningless. Take as an example your `AMuon`. One of the insertions you get (part of `vertices` list inside of `AMuon` function) is the following:
```
{Fe, hh, bar[Fe]}, {bar[Fe], hh, Fe}, {VP, Fe, bar[Fe]}
```
Clearly it doesn't make any sense if you feed those lists to Vertex function. Now, this does work for you in `AMuon` case by accident. Because
```
Vertex[{Fe, hh, bar[Fe]}] = Vertex[{bar[Fe], hh, Fe}]
```
If you'd try to do the same with a vector and a not scalar (Higgs in the example above), you'd have to carefully flip left and right parts and add some signs. Hope this explains our doubts. No one is saying that your code for `AMuon` is wrong. It's that we need to figure out a generic procedure how to handle stuff in the future. I am not able to modify the adjacency matrix to get the order that I want, even though I tried. The use of `SortCp` might also be problematic, because sometimes one does actually want those weird field orders. Just not in the example above.

**Comment by iolojz** [comment]
I see your concerns. But it sounds to me like you yourself do not know what
a generic solution would be supposed to do. e.g if one always applied a
standard ordering by field types, like e.g F*FS or F*FV, one would lose the
information about which fields are internal as well as the directions of
propagators. Of course this information could be passed separately, but
then a c++ function for eg. amu would need (at least) three switches for
checking propagator directions and a further three to properly map them to
the reordering applied to the vertices.

The way it is done now, that information is always available albeit in the
very compressed form of the "weird" vertices and the adjacency matrix. That
way, for every problem you have a fixed convention that you only need to
translate once to that of your paper and there is no need for switches.

What might be problematic is of course that this does not scale well: n
diagram classes will need n translations of conventions. But, and that is
my firm belief, because papers do not always use the same conventions, you
can never get a better scaling than n anyway!

**Pull request merged**
