### PR TITLE
NpointFunctions: Add option to disregard the cache

### PR DESCRIPTION
**Pull request by SoundSonic1**
As a developer, the caching option is quite annoying since you always have to remove the old cache by hand anytime you change something in the NPointFunctions module. In addition, the test suite should also not look for the cache.
@iolojz can you have a look at this?

### CODE REVIEW

**Comment by iolojz** [comment]
This is a good idea! I would rather have it though, that if a user (developer) decides to not check the cache, it also should not store the result in the cache.
- Could you rename the option to `UseCache` and also place an if around the call to `CacheNPointFunction[]` at the end of the function.

However, I do not see the point for the test suite to not use the cache. Why would one want that?

**Comment by iolojz** [comment]
@Expander What is your opinion on this?

**Comment by Expander** [comment]
For the tests I wouldn't mind if they take a bit longer but are guaranteed to always check the right thing.

**Comment by pathron** [comment]
I strongly agree with Alex that the test suite should not read the cache.

**Comment by iolojz** [comment]
Alright, then.

**Comment by Expander** [comment]
@iolojz Are you ok with the changes up to (including) commit 
362ffd6 ?

**Comment by iolojz** [comment]
Yes it looks good. Just one more tiny thing: Please export the option `UseCache` like the other options to `NPointFunction[]`.

**Pull request merged**
