### PR TITLE
correctly subtract SM contribution to mW

### PR DESCRIPTION
**Pull request by wkotlarski**
TODO:

- [x] don't include the whole length 1 CP-even Higgs multiplet in the BSM part
- [ ] what to do with multiplets of length > 1?

### CODE REVIEW

**Comment by Expander** [comment]
One remark: In [PBMZ](https://arxiv.org/abs/hep-ph/9606211v3) the Higgs contribution to $\delta_{VB}$ is not included in $\delta_{VB}^{SUSY}$. So, this bug fix is correct from this point of view.

Open question: Is the SM Higgs contribution part of $\delta_{VB}$? If yes, then we must be careful not to include the SM-Higgs contributions twice by adding BSM Higgs multiplets to $\delta_{VB}^{SUSY}$ that include the SM-Higgs. If not, then we can simply add BSM Higgs multiplet contributions to $\delta_{VB}^{SUSY}$ without getting a double counting.

**Comment by wkotlarski** [comment]
I think that whether `delta_vb_bsm` should include SM part or not depends on where it's used. It's used twice. Once in the calculation of $m_W$ from the fit formula
```cpp
return mwSM * Sqrt(1.0 + sinThetaW2 / (cosThetaW2 - sinThetaW2) *    
                    (cosThetaW2 / sinThetaW2 *    
                     (delta_rho_hat_BSM + delta_rho_hat_tree)    
                     - delta_rw_hat_BSM - delta_alpha_hat_BSM));
```
Here the SM Higgs should be already included in the result from the fit. And second in the `calculate_delta_vb`
```cpp
double CLASSNAME::calculate_delta_vb(double rhohat_ratio, double sinThetaW) const
{
   const double deltaVbSM = calculate_delta_vb_sm(sinThetaW);

   const double deltaVbBSM = include_dvb_bsm ?
      calculate_delta_vb_bsm(sinThetaW) : 0.;
 
   const double deltaVb = rhohat_ratio * (deltaVbSM + deltaVbBSM);
      
   return deltaVb;
}
```
Here `calculate_delta_vb_sm` doesn't include SM Higgs. Side question: isn't C.12 just an aproximation? As in - it **should** contain the Higgs contribution, its just that it's know to be tiny so BMPZ didn't include terms proportional to electron Yukawa. They've only included two-loop terms proportional to the top Yukawa.

**Comment by Expander** [comment]
> Side question: isn't C.12 just an aproximation? As in - it **should** contain the Higgs contribution, its just that it's know to be tiny so BMPZ didn't include terms proportional to electron Yukawa. They've only included two-loop terms proportional to the top Yukawa.

I have checked the original references from A. Sirlin et.al. where the box contributions are calculated. They say explicitly that they include only $O(\alpha)$ contributions, i.e. gauge coupling contributions. Yukawa contributions are not included. So, you are right: `calculate_delta_vb_sm(sinThetaW)` should include the Higgs contribution, but they are neglected.

**Comment by wkotlarski** [comment]
Then I think we agree that it's all consistent. The weak mixing angle is computed within an approximation where `Ye` is neglected while the $m_W$ in the autogenerated SM is now by definition equal to the result from the fit formula. But what about other models? I believe there is no problem when it comes to CP-even Higgs and weak mixing angle. But for $m_W$ there's a potential double counting. I'm saying potential because the fit formula probably doesn't include this contribution as it's so tiny.

**Comment by Expander** [comment]
You are right w.r.t. the potential double counting. One question, though: Are all terms that are potentially double counted of the order of the electron Yukawa coupling?

**Comment by Expander** [comment]
W.r.t. the calculation of $M_W$: In our paper we take the SM contribution and add the BSM contribution on top. The BSM contribution has been obtained by calculating the full model contribution and subtracting the full SM contribution. This should be fine, I think, i.e. there should be not double counting there.

One interesting point is: In our calculation of the BSM contribution to $M_W$ we use running the weak mixing angle calculated as discussed above. Since the weak mixing angle does not suffer from a double counting (see our arguments from above), there should be not double counting in the BSM contribution in the end.

Or am I overlooking something?

**Comment by Expander** [comment]
Sorry, I don't get it. Do you mean the term $\delta_{VB}^{BSM}$ in Eq.(9) of our MW paper? This term may contain contributions from all Higgs bosons, potentially including the SM Higgs in models where the SM Higgs mixes with others. I.e. it is not a *pure BSM* contribution?

**Comment by wkotlarski** [comment]
Yes. And this is ok **only** because $\delta_{VB}^{BSM}$ is a pure 1-loop quantity and $\delta_{VB}^{SM}$ doesn't contain Higgs contribution at the one-loop level. I think that techically a more correct way of doing this would be to add the SM Higgs contribution proportional to $Y_e$ to $\delta_{VB}^{SM}$ and subtract it from the $\delta_{VB}^{BSM}$. This makes almost no difference numerically. I'm only trying to understand what we do, because it seems that this separation into SM and BSM is not 100% correct.

**Comment by Expander** [comment]
I think what you say is completely correct. I.e. the current implementation is correct, but one could argue that it may be correct "by accident".

Your proposal is a good idea in principle. OTOH, one could argue that this is a complication that is actually not necessary. It could be simpler to just omit the (known) SM-Higgs contribution from $\delta_{VB}^{SM}$ and add the full (SM+BSM)-Higgs contribution in $\delta_{VB}^{BSM}$. This is always correct by construction. (However, the naming of the symbols $\delta_{VB}^{SM}$ and $\delta_{VB}^{BSM}$ then does not match precisely their content.)

**Comment by wkotlarski** [comment]
In principle I don't mind the splitting between $\delta_{VB}^{SM}$ and $\delta_{VB}^{BSM}$ which, as you say, after you add them up doesn't matter. The problem is that $\delta_{VB}^{BSM}$ is used in two places: to fix EW parameters (there we add $\delta_{VB}^{SM}$ and $\delta_{VB}^{BSM}$) and in the $m_W$  calculation (here we don't add $\delta_{VB}^{SM}$). Including $Y_e$ contributions in $\delta_{VB}^{BSM}$ means we don't reproduce SM $m_W$. Unless we add this junky fix from this PR. Then we do (in all models where the CP-even Higgs sector is the same as in the SM) but not in others.

**Comment by Expander** [comment]
Ah, you are right! In the calculation of $M_W$ it matters in principle.

If I understand this PR, it excludes the SM Higgs from $\delta_{VB}^{BSM}$, right? The criterion for the exclusion is the returned value of `IsSMHiggs`. This function returns true only in models where the SM Higgs can be clearly defined, i.e. when there is no mixing. So, in the 2HDM or in the MSSM you'd still include the CP-even Higgs multiplet `hh` in $\delta_{VB}^{BSM}$, right?

**Comment by wkotlarski** [comment]
Correct. For example in the SM we get
```cpp
std::complex<double> CLASSNAME::delta_vb_wave_Fe(int gO1) const
{
   
   const std::complex<double> result = 0;

   return result;
}

```
while in the SSM we get
```cpp
std::complex<double> CLASSNAME::delta_vb_wave_Fe(int gO1) const    
{    
   const auto MFe = MODELPARAMETER(MFe);    
   const auto Mhh = MODELPARAMETER(Mhh);    
    
   const std::complex<double> result = SUM(gI1,0,1,SUM(gI2,0,2,-(AbsSqr(    
      CpbarFeFehhPL(gI2,gO1,gI1))*B1(0,Sqr(MFe(gI2)),Sqr(Mhh(gI1))))));    
    
   return result;    
}
```

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
Ok, perfect, thanks! :)

**Pull request merged**
