### PR TITLE
moved model independent cxx_qft things from templates to src

### PR DESCRIPTION
**Pull request by wkotlarski**
This fixes the `CMSSMSemiAnalytic_consistent_solutions` test.

### CODE REVIEW

**Comment by wkotlarski** [comment]
I've added @uukhas as reviewer since I had to fix some `npointfunctions` tests after my changes.

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
Looks good to me, thanks!

**Comment by wkotlarski** [comment]
To explain to Vova what happened: I've split `MODELNAME_cxx_diaggrams` stuff into a model independent and a model dependent parts. This avoids duplication and clashes if you load two models at the same time. So concepts like `conj`, `bar` or `ChiralVertex` are model independent. What is model dependent are specializations of `conj` etc. I think that the main change from the point of view of `npointfunctions` is that `conj` and `bar` don't live in `MODELNAME_cxx_diagrams` anymore. They are in `cxx_diagrams`. So wherever you used `bar` and `conj` inside of `MODELNAME_cxx_diagrams` namespace you can now do
```cpp
namespace MODELNAME_cxx_diagrams
{
using cxx_diagrams::conj;    
using cxx_diagrams::bar;
...
}

**Comment by uukhas** [comment]
Great idea, I like it. @wkotlarski, am I assumed to merge these changes into my current branch and look what you have broken for the NPointFunction calculations?

**Comment by wkotlarski** [comment]
If you would be so kind :smile:

**Comment by wkotlarski** [comment]
I think I'm done with this PR. I'm only waiting for ok from Vova.

**Comment by wkotlarski** [comment]
@uukhas, is it ok to merge it?

**Comment by uukhas** [comment]
> @uukhas, is it ok to merge it?

Let me check first. I did not work with git for a while.

**Pull request merged**
