### PR TITLE
let mathlink set observables settings

### PR DESCRIPTION
**Pull request by wkotlarski**

### CODE REVIEW

**Comment by wkotlarski** [comment]
Does the second part make sense? Because in the end I want to modify `Spectrum_generator_settings`. So I have to make a copy.

**Comment by Expander** [comment]
Yes, if you want to modify it, you have to make a copy.

However, if one just wants to read a value, a const reference would be sufficient. In this case, returning a const reference would be more performant. So, in general I'd prefer to return a const ref for structs from const functions.

**Comment by wkotlarski** [comment]
Is it ok now?

**Comment by Expander** [comment]
If I'd be pedantic, I'd recommend to use west-const (not east-const) for consistency.  :)

**Comment by wkotlarski** [comment]
Anything else?

**Comment by Expander** [comment]
Many thanks, that is perfect! :) Please feel free to merge it.

**Comment by wkotlarski** [comment]
I'll squash it, wait for tests to pass and then merge it. Thanks a lot for checking it!

**Pull request merged**
