### PR TITLE
Feature mass eigenstates interface

### PR DESCRIPTION
**Pull request by wkotlarski**
I've changed the `context_base` to operate on the interface. The tests are passing.

### CODE REVIEW

**Comment by Expander** [comment]
Does this mean, that you're using the interface in the decay calculation and everything works? Very nice!

Is the default still the non-decoupling model?

**Comment by wkotlarski** [comment]
Yes. Through the weekend I've cleaned the code to bring it more in line with the upstream and so I'd like to start moving small parts into the main repo.

**Comment by Expander** [comment]
Amazing, that all the tests work out!

For me, this PR is fine and can be merged.

**Comment by Expander** [comment]
Shall we squash-and-merge it?

**Pull request merged**
