### PR TITLE
less messy sarah output to terminal

### PR DESCRIPTION
**Pull request by uukhas**
Allows to have cleaner terminal output of `SARAH`.

In this package some `Dynamic` were upvalued, so that inside terminal there is no "broken" output from `SARAH`.

### CODE REVIEW

**Comment by wkotlarski** [comment]
For me it's fine.

**Comment by uukhas** [comment]
Now everything seems to be fine.

**Comment by wkotlarski** [comment]
@Expander, are you ok with this PR?

**Comment by Expander** [comment]
That's a very nice feature!

Only two questions:

* Do you think this is forward compatible with future SARAH versions?
* I'm wondering if the hidden information is important to a user. What is your opinion?

**Comment by uukhas** [comment]
@Expander,

this additional package changes only `Dynamic` output from `SARAH` by defining delayed up values for some terminal output. 

-  it is quite unlikely, that some core `Mathematica` output of `SARAH` of definitions for Lagrangian, generation of vertices, or beta functions will be changed. If some new additional features will be defined by `SARAH`, then they can be easily added into the full list of delayed definitions in this package.

-  This package hides only the information which leaks to **terminal only**, because `Dynamic` is not working with it appropriately. So, nothing, which is shown with `Notebook` interface is hidden, it is only transformed to a more compact form.

**Comment by Expander** [comment]
@uukhas thanks for the clarification! From my point, this PR can be (squashed-and) merged.

**Comment by uukhas** [comment]
@Expander, do I understand correctly, that now somebody with _writing_ privileges has to press the button you mentioned and I do not need to recombine these 4 commits explicitly?

**Comment by Expander** [comment]
Sorry, I wanted to wait for comments. :)

**Pull request merged**
