### PR TITLE
make FlexibleDecay tests read the entire SLHA output

### PR DESCRIPTION
**Pull request by wkotlarski**
@Expander, I can get everything to work but I'm worried about one thing. For most of the decays the changes (as you can see) are < 1% which is reasonable. For some however they are really large. Especially weird is maybe `MSSMCPV`. It says now that the vertex h(1)WW is 0... h(0) is a Goldstone. h(1) is a normal Higgs...

### CODE REVIEW

**Comment by Expander** [comment]
I have noticed the same. I found that this was due to some small changes in the SLHA output: The hard-coded SLHA strings did not match exactly the output of calling `.run()`. Then there is also this limited precision of the SLHA output to ~8 digits.
Could it be that some decays are simply very sensitive to these small changes?

**Comment by wkotlarski** [comment]
There are maybe 2 separate things. Some might indeed be sensitive. But here the problem is simpler. The h(1)-W-W vertex which is just g2 times some mixing matrix elements and vevs is set to 0. This cannot be right, right?

**Comment by wkotlarski** [comment]
Why would the mass be set to 0 if we add it to the `MASS` block? The reason why I've added SM masses to the `MASS` block is exactly opposite. Without them SM fermions are massless.

**Comment by Expander** [comment]
Sorry for the confusion. We are reading all pole masses from the `MASS` block. However, the one for W is missing. So, in the model the W pole mass is not set to a non-zero value, so it remains at its initial value (= zero).

**Comment by wkotlarski** [comment]
I'm sorry @Expander, but what you're saying is not true. The SLHA string now has
```
Block MASS
1000021     2.12248650E+03   # Glu
     24     8.03577013E+01   # VWm
...
```

**Comment by Expander** [comment]
Sorry, I think I misunderstood you, because of the usual 0 vs 1 index issue. :)
Are you saying that the test for the 2nd Higgs `hh(1)` (C index convention) fails?

**Comment by wkotlarski** [comment]
Yes. The `hh(1)-W-W` vertex (in C convention) is 0.

**Comment by wkotlarski** [comment]
Vertices are computed from tree-level mixings. But at the tree-level
```
ZH =  0.205689  0.978617         0         0
        0         0 -0.204969  0.978768
        0         0  0.978768  0.204969
 0.978617 -0.205689         0         0
```
So hh(1) is a pure pseudoscalar.

**Comment by Expander** [comment]
Yes, we do that! In `MSSMCPV_mass_eigenstates.cpp` we have:
~~~.cpp
/**
 * reorders pole masses so that golstones are placed at the index
 * specified in the model files definition of the associated
 * gauge boson (see Z-boson definition in default particles.m file
 * in the Models directory of your SARAH distribution for example)
 */
void CLASSNAME::reorder_pole_masses()
{
   move_goldstone_to(0, MVZ, PHYSICAL(Mhh), PHYSICAL(ZH));
   move_goldstone_to(0, MVWm, PHYSICAL(MHpm), PHYSICAL(ZP));
}
~~~
So, the entry `i` in `PHYSICAL(Mhh)`, for which `PHYSICAL(Mhh)(i) == MVZ`, is moved to position `i == 0`.

However, this function compares the DR-bar mass `MVZ` to the pole masses in `PHYSICAL(Mhh)`.
Could it be that the entry `PHYSICAL(Mhh)(i) == 81.9029` is closer to `MVZ` than the entry `PHYSICAL(Mhh)(i) == 89.4304`?

**Comment by wkotlarski** [comment]
Fun fact: calling `m.reorder_DRbar_masses()` just after `m.calculate_DRbar_masses()` fixes tests for hh(1)->WW and hh(1)->ZZ (they give the same numerical values as before any changes).

**Comment by Expander** [comment]
I'm suspicious that it might be that we call `calculate_Mhh_DRbar()` or `calculate_Mhh_pole()` without following this by a call to `reorder_DRbar_masses()` or `reorder_pole_masses()`.

**Comment by wkotlarski** [comment]
I think we had this discussion. I don't like that there are commands that leave generator in an incostitant state and you have to remember to call them in pairs. But I've accepted is the price of flexibility. I'll add them to all FlexibleDecay tests, even ones that seemed to work.

**Comment by Expander** [comment]
I agree, this is error prone and I'm thinking about how to avoid such issues.

**Comment by wkotlarski** [comment]
All tests are now fixed. I'll review the changes and let you know when I think we can merge it.

**Comment by wkotlarski** [comment]
I've checked the change log:

- In the `MSSMCPV` and the `THDMII` results shifted only by small fraction (so I consider them solved :+1: ).
- `MRSSM2` is also fine apart from sgluon decays which shifted a lot (sigmaO -> ttbar shifted by 50%, others much less).
- In the `MSSM` differences are substantial, and they are in all places :-1:

**Comment by wkotlarski** [comment]
`MRSSM2` is solved. Only `MSSMCPV` is left.

**Comment by wkotlarski** [comment]
@Expander, there's an odd thing in reading the whole SLHA spectrum from a string. `MSSM` test results change depending on whether the block `MSOFT` is present or not. For me this makes no sense as it's only of extra outputs from `ExtraSLHAOutputBlocks`.

**Comment by Expander** [comment]
In `models/MSSM/MSSM_slha_io.cpp` there is the function
~~~.cpp
void MSSM_slha_io::fill_drbar_parameters(MSSM_mass_eigenstates& model) const
{
   // ...
   model.set_mHd2(slha_io.read_entry("MSOFT", 21));
   model.set_mHu2(slha_io.read_entry("MSOFT", 22));
   model.set_MassB(slha_io.read_entry("MSOFT", 1));
   model.set_MassWB(slha_io.read_entry("MSOFT", 2));
   model.set_MassG(slha_io.read_entry("MSOFT", 3));
}
~~~
which reads the soft-breaking Higgs mass parameters and the gaugino mass parameters from `MSOFT`.
Is there a difference between the values of the input parameters in `MSOFT` and in other blocks?

**Comment by wkotlarski** [comment]
Oh, I thought `ExtraSLHAOutputBlocks` contains only observables. Yes, there's a difference because it's a highscale model. So it's
```
Block EXTPAR    
     0     1.94220000E+16   # Qin    
    21     1.56250000E+04   # mHd2IN    
    22     1.56250000E+04   # mHu2IN
```
vs.
```
Block MSOFT Q= 8.61574711E+02
    ...
    21     1.12097875E+05   # mHd2
    22    -3.87890853E+05   # mHu2
```

**Comment by Expander** [comment]
Ok, then this difference is to be expected. The question is, which values do you want to use?

**Comment by wkotlarski** [comment]
What I'd like is to read a spectrum at the low scale (here `Q = 8.61574711E+02`). If I only read high scale boundary conditions then it doesn't make sense because then I have to run the spectrum generator again.

**Comment by Expander** [comment]
Ok, then you'd have to keep the `MSOFT` block, because it contains the parameters you'd like to input.

**Comment by wkotlarski** [comment]
So that part I understand. Moving on. Do you know how it happened that in the spectrum for the `MSSM` we had
```
Block MASS
...
24     8.22179853E+01   # VWm
```
but because we didn't read this mass but were computing it again we used `80.3634`. This difference explains all deviations in decays to WW and probably also ZZ, and gammaZ.

**Comment by Expander** [comment]
Sorry, I have no idea why we had such a low value for MW. I would guess, however, that the calculation that was used to obtain it was some imprecise one, maybe with non-decoupling higher-order contributions from prior FS 2.5.0?

**Comment by wkotlarski** [comment]
The tag says 2.4.1. So I'll adopt the channels where I can guess what caused the change and see what will be left.

**Comment by Expander** [comment]
Ok, in 2.4.1 we had the old 1-loop calculation with non-decoupling dirt effects.

**Comment by wkotlarski** [comment]
Ok. I think it now works. I had to regenerate the SLHA output and now the changes look reasonable. I'll check the numbers again in the afternoon and we should be able to merge it today/tomorrow.

**Comment by wkotlarski** [comment]
@Expander, I'm done. Can I merge it?

**Comment by Expander** [comment]
Yes, please! Thanks a lot!

**Pull request merged**
