### PR TITLE
replace generate_scales by subdivide_log

### PR DESCRIPTION
**Pull request by Expander**
to avoid repetition

### CODE REVIEW

**Comment by wkotlarski** [comment]
I've added a test for the calculation of the uncertainty. You might want to merge the dev branch in to see if it still works after your change. Other than that I'm ok with this change. Thanks :)

**Comment by Expander** [comment]
I get the following errors from `test/test_MRSSM2_gmm2.x`:
~~~
test/test_MRSSM2_gmm2.cpp(69): error: in "test_amu": difference{2.07207e-05} between ae{-1.8018990568230194e-15} and -1.8019363934392491e-15{-1.8019363934392491e-15} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(72): error: in "test_amu": difference{2.08533e-05} between amu{-8.1717403498114888e-11} and -8.1719107571588341e-11{-8.1719107571588341e-11} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(75): error: in "test_amu": difference{8.9575e-05} between damu{9.0683676308516157e-13} and 9.0675554049399791e-13{9.0675554049399791e-13} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(78): error: in "test_amu": difference{0.000236846} between atau{-2.2077201448856852e-08} and -2.2071973783347808e-08{-2.2071973783347808e-08} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(85): error: in "test_amu": difference{1.95187e-05} between ae{1.3730375643314638e-16} and 1.3730107649079216e-16{1.3730107649079216e-16} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(88): error: in "test_amu": difference{2.84112e-06} between amu{6.2697973755178966e-12} and 6.2697795623223974e-12{6.2697795623223974e-12} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(92): error: in "test_amu": difference{0.00162981} between atau{3.7243232386298135e-09} and 3.7303931716651099e-09{3.7303931716651099e-09} exceeds 9.9999999999999995e-08
test/test_MRSSM2_gmm2.cpp(95): error: in "test_amu": difference{1.382e-05} between damu{7.2780475609845985e-12} and 7.277946979761437e-12{7.277946979761437e-12} exceeds 9.9999999999999995e-08
~~~
To reproduce:
~~~
./createmodel --name=MRSSM2 -f
./configure --with-models=MRSSM2 --with-optional-modules=test --with-gm2calc-incdir=$HOME/research/GM2Calc/include --with-gm2calc-libdir=$HOME/research/GM2Calc/build/lib
make -j4 && make test/test_MRSSM2_gmm2.x && test/test_MRSSM2_gmm2.x
~~~

**Comment by Expander** [comment]
I have checked that I get exactly the same errors on the `development` branch. So, my changes are not related to the test failure of `test/test_MRSSM2_gmm2.x`.

**Comment by wkotlarski** [comment]
Are you sure? The tests on development go through fine.

**Comment by Expander** [comment]
> Are you sure? The tests on development go through fine.

Yes, on commit f47c45b1dba9b5fb03bdfb4407800e315f6bcb0d the MRSSM test fail for me, as above. It may be a numerical issue, maybe related to slightly different optimizations on our two machines.

**Comment by wkotlarski** [comment]
I don't know if you want to do something with it. Here it seems that everything works (including tests on this branch).

**Review by wkotlarski — APPROVED** [review]

**Comment by Expander** [comment]
> I don't know if you want to do something with it. Here it seems that everything works (including tests on this branch).

One thing we could do is to relax the test precision accordingly, as this seems to be a numeric effect and as such the last digits seem to be garbage anyway.

**Pull request merged**
