### PR TITLE
Require C++17

### PR DESCRIPTION
**Pull request by wkotlarski**
Using `HiggsTools` will require moving to C++17

### CODE REVIEW

**Comment by Expander** [comment]
I think we should first look which operating systems/distributions ship with a C++-17 compatible compiler, before we can require it.

**Comment by wkotlarski** [comment]
I know. I don't expect this change to be made now. Consider this PR as a conversation starte :wink: (and a check that going to C++17 doesn't blow up the entire code)

**Comment by wkotlarski** [comment]
An alternative would be to have a temporary middle step as @pathron sugested here https://github.com/FlexibleSUSY/FlexibleSUSY/issues/253#issuecomment-1034398376_:

1.  check used compiler
2. if it supports it - use c++17
3. if it doesn't - use c++14 and disable `HiggsTools` interface

**Comment by pathron** [comment]
Yes sorry for not replying earlier> I think this is a perfectly fine solution while we wait for   c++17 to "come of age" :).

**Comment by wkotlarski** [comment]
@Expander, I know you enjoy coding in bash. Would you mind implementing it on `feature-HiggsTools-interface`? Schematically:
```
if gcc or clang > ? => -std=c++17
else -std=c++14 & override ENABLE_HIGGSTOOLS
```

**Comment by Expander** [comment]
> @Expander, I know you enjoy coding in bash. Would you mind implementing it on `feature-HiggsTools-interface`? Schematically:
> 
> ```
> if gcc or clang > ? => -std=c++17
> else -std=c++14 & override ENABLE_HIGGSTOOLS
> ```

W.r.t. `HiggsTools` you mean to disable it if C++17 is not supported?

**Comment by Expander** [comment]
From looking at https://en.cppreference.com/w/cpp/compiler_support/17 it seems that C++17 is available/complete since
* gcc >= 7
* clang >= 4

Concerning the (stable) OS that have gcc and clang:
* Debian stable: gcc 10.2, clang 11.0
* OpenSUSE: gcc 14
* Ubuntu LTS (bionic): gcc 8, clang 10

So, I think it is safe to make a C++17 compatible compiler a requirement.

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
fixes #540

**Comment by Expander** [comment]
I would **very much** in favor of it! :)

**Comment by Expander** [comment]
Could you please add an entry in `CHANGES.rst` to say that we now require C++17?

**Comment by wkotlarski** [comment]
Done. Unless someone objects I will merge it after all tests pass.

**Comment by Expander** [comment]
Actually, I have one more wish, sorry. :)
Please remove all lines that contain `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`.
They are obsolete now.

**Comment by Expander** [comment]
Please feel free to merge it then!

**Pull request merged**
