### PR TITLE
2-loop non-QCD contributions to running SM top mass

### PR DESCRIPTION
**Pull request by Expander**
Note that the corrections require [TSIL](https://www.niu.edu/spmartin/TSIL/) to be installed. TSIL must be compiled with `-fPIC`.

The corrections have been extracted from the Mathematica file(s) published with [arXiv:1604.01134].

Authors: [Harun Acaroglu](https://github.com/harunresiderzurumi/Master-Thesis) and Alexander Voigt

### CODE REVIEW

**Comment by pathron** [comment]
This breaks basic code generation for me.  Building the CMSSM on this branch with tsil disabled automatically (ie on a machine which does not have tsil installed) and I get errors:

models/CMSSM/CMSSM_mass_eigenstates.cpp:18:122: error: expected unqualified-id before ‘return’
                                                                                                                          return m_susy_drbar;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }                                                                                                                                         return ArcTan(ZH(1,1)/ZH(0,1));
                                                                                                                          ^
models/CMSSM/CMSSM_mass_eigenstates.cpp:18:684: error: expected declaration before ‘}’ token
                                                                                                                          return m_susy_drbar;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }                                                                                                                                         return ArcTan(ZH(1,1)/ZH(0,1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^

and also a bunch of warnings that are quite similar.

Using mathematica 11.1 with SARAH 4.12.3 and mathematica 11.2  with SARAH 4.12.2.

It builds fine for development.

**Comment by Expander** [comment]
Thanks for catching this bug! I've pushed a fix. Would you mind re-running?

**Comment by pathron** [comment]
Yes that fixes it, thanks. I still need to review the code though.

**Comment by Expander** [comment]
Hi Peter,

many thanks for testing so far!

Concerning your questions:

1. Yes, the `_spheno` variants are just for testing and could thus be removed. (But I don't see a strong reason for that at the moment.) Btw., Harun found that the difference between the `_flexiblesusy` and `_spheno` calculations is negligible in the SM (and should not be used as an uncertainty estimate). This is in contrast to the MSSM, where their difference is a good estimate of the uncertainty.

2. The flags `-O3 -funroll-loops` is the TSIL default. This is why I wrote it. I wanted to avoid saying "Pleas set `TSILOPT = -fPIC`", because then the user may omit the optimization flags. OTOH, saying "please add -fPIC to `TSIL_OPT`" would be too vague and I wanted to give a full example. This is why I gave a concrete example with all compiler flags.

Yes, it would be nice if you could test also with TSIL enabled. Then you could build `HSSUSY` and run the following point:

    ./models/HSSUSY/run_HSSUSY.x --slha-input-file=model_files/HSSUSY/LesHouches.in.HSSUSY | grep hh

**Comment by pathron** [comment]
OK so installed still and tried to build it with:

./configure --with-models=HSSUSY --with-himalaya-incdir=/home/pathron/software/Himalaya/source/include --with-tsil-incdir=/home/pathron/software/tsil-1.43 --with-tsil-libdir=/home/pathron/software/tsil-1.43
make -j20 >& make.log

Unfortunately I get errors that look like problems with my std libraries, maybe some gcc vs g++ thing, e.g.

/usr/include/c++/5/bits/cpp_type_traits.h:72:3: error: template with C linkage
   template<typename _Iterator, typename _Container>
   ^
/usr/include/c++/5/bits/cpp_type_traits.h:85:3: error: template with C linkage
   template<bool>
   ^
/usr/include/c++/5/bits/cpp_type_traits.h:89:3: error: template specialization with C linkage
   template<>
   ^
/usr/include/c++/5/bits/cpp_type_traits.h:95:3: error: template with C linkage
   template<class _Sp, class _Tp>
 
I am using g++--5.4 for FlexibleSUSY and gcc-5.4 for tsil.  i may try playing around with g++/gcc versions after my next meeting, but let me know if you have some idea
[make.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/3083170/make.log)
. 



p.s. I find it a bit odd that I still needed to give a path to tsil directories even after doing make install for tsil, but reading the README more carefully it seems that is just a tsil problem because that they didn't design make install to also copy over    

 tsil_cpp.h
 tsil_fort.inc 

and looks like you just have to do that manually if you want to use it with c++ or fortran without specifying paths to the headers.

**Comment by Expander** [comment]
Hi Peter,

many thanks for testing! I suspect I know what's the problem: Would you mind modifying `tsil.h` by moving the lines
~~~
#ifdef __cplusplus
extern "C" {
#endif
~~~
_behind_ the `#include` directives? The resulting `tsil.h` file should read:
~~~
#ifndef _TSIL_H_
#define _TSIL_H_

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <float.h>
#include <complex.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Select basic floating point data size: */
~~~
Then please run `make clean` and `make` in the TSIL directory.

If this fixes the compilation with FS, then we may report this issue to S. Martin and Robertson.

Many thanks and best regards,
Alex

**Comment by pathron** [comment]
OK I had already installed gcc-6.5 and g++-6.5 before I saw this (and then had to reisnstall gfortran because that deleted it...nice). Everything compiles finw with 6.5 and I get:

$ ./models/HSSUSY/run_HSSUSY.x --slha-input-file=model_files/HSSUSY/LesHouches.in.HSSUSY | grep hh
        25     1.24955371E+02   # hh

**Comment by pathron** [comment]
So trying your solution with g++-5 gets rid of the errors I pasted above but it has other errors (which I think also appeared in the make.log I attached earlier):

model_specific/SM_thresholds/sm_twoloop_mt.cpp:581:38: error: no match for ‘operator*’ (operand types are ‘TSIL_COMPLEXCPP {aka std::complex<long double>}’ and ‘double’)
       + 4.0L*(SigmaS(t, h, yt, t, qq)*sqrt(t)

[makeg++5.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/3083689/makeg%2B%2B5.log)

**Comment by Expander** [comment]
Hi Peter,

many thanks again! You get exactly the number I get.

One last thing: I've pushed a change in the hope that it now compiles with g++-5. Could you please try to re-compile with this fix with g++-5?

**Comment by pathron** [comment]
Yes that works!  Though it will still give errors without your change to tsil.h, so it would still be a good idea to write a bug report to them.

**Comment by Expander** [comment]
Perfect, many thanks!

Is the branch read to be merged? In particular, is the way ok, in which we require TSIL as a dependency (including the extra build requirement `-fPIC` for TSIL)?

I will write a bug report to the TSIL author and put you into the CC.

**Comment by pathron** [comment]
I think it is OK. What else could we do?  Maintain a patch to add this to the makefile and a little script to download and build it automatically for them?  I feel like that is a bit much for this? or you have some other idea?

**Comment by Expander** [comment]
Hi Peter,

I also think this would be a bit too much. Also, I hesitate a bit the maintenance of such a script. :)

TBH, I think it would be good if the HEP community would go towards using a package manager, like [conan](https://conan.io/) or so. In this way it would be very easy for everybody to install the dependencies. FS would also benefit from this if we'd switch to cmake, because then our build procedure would be much easier.

**Comment by Expander** [comment]
Hi Peter,

do you think this branch can be merged anyway?

P.S.: Concerning the dependency issues, I'm currently experimenting with [conan](https://conan.io/) package manager. Contrary to my previous statement, conan can work with any build system (CMake, autotools, meson, make, ...).

For test purposes I've created a [conan package for TSIL](https://github.com/conan-hep/conan-tsil). It works nicely with CMake, meson and make and can be easily integrated into FS. Maybe we can discuss this in our next FS-code meeting?

**Comment by pathron** [comment]
Yes please do merge!

Regarding conan, sounds great, yes lets discuss it in the next meeting.

**Pull request merged**
