### PR TITLE
use the user-provided precision in the root finder and minimizer

### LINKED ISSUE #418: FindRoot[] Precision
If one use the function FindRoot[] in the FlexibleSUSY.m.in file to fix a parameter, then in the file <Model_Name>_two_scale_susy_scale_constraint.cpp the function root_finder() is called.  This function takes the magic number input 1.0e-2 as a precision.  It would be better if this was fixed to the inputted precision in the SLHA file.

### PR DESCRIPTION
**Pull request by Expander**
Fixes #418

### CODE REVIEW

**Comment by Expander** [comment]
@dhjjacob Are you ok with this change?

**Comment by dhjjacob** [comment]
Hi @Expander, looks good.  There is an additional issue that @pathron and myself spotted when investigating this function over the weekend.  We noticed that the `status` outputted by root_finder.find_root() is non-zero, and while it is sent to a verbose message, it does not seem to be handled by any error-catchers.  Can we also handle this here?  What do you think?

**Comment by Expander** [comment]
Thank for the hint! I'll pass the error message to the SLHA output.

**Comment by Expander** [comment]
Ok, I have transported it to the SLHA output as an error.

**Comment by dhjjacob** [comment]
Hi @Expander, looks good to me.  Thanks!

**Review by dhjjacob — APPROVED** [review]

**Pull request merged**
