### PR TITLE
Feature package models

### PR DESCRIPTION
**Pull request by wkotlarski**
@Expander, how should commits to `FlexibleSUSY-generated` and `FlexibleSUSY-slha` be named? For now i called them "new release". Could you check blocks `Commit models` and `Commit SLHA outputs` and adapt them to the way how you'd commit those changes?

### CODE REVIEW

**Comment by Expander** [comment]
Would it be possible to add the version or tag name to the commit message? Like maybe so: `version x.y.z`?

Would it also be possible to create a tag in these repositories?

**Comment by Expander** [comment]
I'm also a bit confused: Where is specified which models to generate? I may have missed it.

**Comment by wkotlarski** [comment]
I've added tags. Do you want annotated or lightweight tag? The models are hard coded in your script.

**Comment by Expander** [comment]
Personally I'd prefer light-weight tags. For me this would be fine, because the commit message already contains the information about the version.

**Comment by wkotlarski** [comment]
@Expander, it's ready for review. Please let me know what you think.

**Comment by Expander** [comment]
That looks very neat!

One question, though: It seems to me that https://github.com/FlexibleSUSY/FlexibleSUSY-slha/tree/test contains fewer SLHA output files than I thought. For example `NUHMSSMNoFVHimalaya` is missing. What is the reason for this?

**Comment by Expander** [comment]
Another question: On https://flexiblesusy.hepforge.org/models.html we had uploaded the tarballs. How can they be accessed? (Sorry if it's a dumb question.)

**Comment by Expander** [comment]
Yes, I usually just copy the generated tarballs to hepforge so a user can download and extract them.

Would there be any way to do the same here? I assume so, because these tarballs get actually created. It's probably just a matter of accessing them, right?

**Comment by wkotlarski** [comment]
Yes, you can add rsync command at the end of `.github/workflows/package-models.yml`

- `rsync -P /tmp/models-artifacts/*.tar.gz ...` in block `upload-models`
- `rsync -P /tmp/slha-output-artifacts/* ...`  in block `upload-slha-outputs`

You can add your hepforge password as a secret to FlexibleSUSY repo.

**Comment by Expander** [comment]
Would there be also the possibility to make these artifacts available on this github repository site?

**Comment by wkotlarski** [comment]
I was thinking about it. I should be possible but I don't yet have a solution. I also would like to make them downloadable together with `FlexibleSUSY.tar.gz`.

**Comment by wkotlarski** [comment]
Packaging models work without a problem as you can see on `FlexibleSUSY-slha` and `FlexibleSUSY-generated`. Also I've created a workflow that will update those extra files to the release. [Here](https://github.com/wkotlarski/FlexibleSUSY/releases/tag/v6.6.34)'s and example output. The way it works is that once the release is published the action is run, zip archive `my-artifact.zip` is created and uploaded. Would you like me to upload every model separately?

**Comment by wkotlarski** [comment]
The drawback of having each model as separate `.tar.gz` can be seen [here](https://github.com/wkotlarski/FlexibleSUSY/releases/tag/v6.6.37). It will be a lot of files and `Source code` might get lost.

**Comment by Expander** [comment]
That method is ingenious and I like it a lot!
We should definitely push every tarball for every model separately, so users can download them separately. 
What do you mean by source code may get lost?

**Comment by wkotlarski** [comment]
Github layout is such that every asset is displayed on separate line. We'll have half a page of models and only a the very end there's going to be actuall FlexibleSUSY.

**Comment by Expander** [comment]
I see. Personally I don't mind that the list would be quite long. What is your opinion?

Would it alternatively be possible to commit these tarballs to the FlexibleSUSY-generated repo? (Just asking in case you are very unhappy with the current solution.)

**Comment by wkotlarski** [comment]
Please check [this](https://github.com/wkotlarski/FlexibleSUSY/releases/tag/v6.6.53) output. From my point of view, this PR is ready to be merged.

**Comment by Expander** [comment]
Perfect, thanks a lot! Please feel free to merge it!

**Review by Expander — APPROVED** [review]

**Comment by Expander** [comment]
Just for my understanding: The tarballs get created when we create a proper github release (not just a tag).

**Comment by wkotlarski** [comment]
Yes. Specifically, when the release is published. This workflow is not triggered by draft releases.

**Pull request merged**
