### PR TITLE
Feature: Automatic installation of dependencies with Conan

### PR DESCRIPTION
**Pull request by Expander**
This pull request implements the automatic installation of FS dependencies with Conan. See README.rst for reference.

## Usage

First, install and setup Conan (if not already done):
~~~
pip install conan
conan remote add conan-hep https://api.bintray.com/conan/expander/conan-hep
~~~
Second, install the FS dependencies (must be executed from within the FS directory):
~~~
conan install . --build=missing -s compiler.libcxx=libstdc++11
~~~
Finally, build your favourite FlexibleSUSY model as usual:
~~~
./createmodel --name=HSSUSY
./configure --with-models=HSSUSY
make -j4
~~~
Note, that it was not necessary to pass any other arguments to `configure`, besides the model to be build. `configure` reads all necessary information from the `*.pc` files generated by Conan.

Finally, run the gorgeous HSSUSY:
~~~
./models/HSSUSY/run_HSSUSY.x --slha-input-file=model_files/HSSUSY/LesHouches.in.HSSUSY
~~~

## Missing package recipes

* Currently there is no Conan package recipe for the GNU Scientific Library. I.e. the GSL must be installed with the package manager of your Linux distribution (this may change in the future):

      sudo apt-get install libgsl-dev

* Currently there is no Conan package recipe for SARAH. However, FS ships an installation script to install SARAH:

      ./install-sarah

* Currently there are no Conan package recipes for FeynArts and FormCalc (which are optional anyway). As described in the README file, they can be installed by:

      cd ~/.local
      wget http://www.feynarts.de/FeynInstall
      chmod 755 FeynInstall
      ./FeynInstall

## Future extensions

*  [conan-hep](https://bintray.com/expander/conan-hep) contains a package recipe for the [COLLIER](https://collier.hepforge.org/) integral library. It may be used in the future instead of LoopTools.

## Resources

The usable Conan package recipes can be found at [bintray](https://bintray.com/expander/conan-hep). This repository can be registered as a "remote" for Conan to download the package recipes needed to download and install the packages. See the above setup commands.

The source code for the Conan package recipes (i.e. the place where changes to the recipes can be made) can be found at the [conan-hep](https://github.com/conan-hep) github site organization. Feel free to contribute! :)

### CODE REVIEW

**Comment by wkotlarski** [comment]
I will have to look into it more closely but as a quick check this doesn't work for my system. It complains that `package gfortran is not installed` and wants to get access to my package manager. Needles to say, `gfortran` is installed.

**Comment by Expander** [comment]
Ouch! Could you please upload the output of Conan so we can trace the issue?

**Comment by wkotlarski** [comment]
The console output is not very informative. Also, it refers to my distro so some stuff is in Polish :)
```
wojciech@kompek:~/Programowanie/c++/FlexibleUpstream> conan install . --build=missing -s compiler.libcxx=libstdc++11
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

WARN: Himalaya/2.0.1@conan/stable requirement eigen/[>=3.0]@conan/stable overridden by your conanfile to eigen/3.3.7@conan/stable 
Version ranges solved
    Version range '>=1.37.0' required by 'conanfile.txt' resolved to 'boost/1.70.0@conan/stable'
    Version range '>=3.1' required by 'conanfile.txt' resolved to 'eigen/3.3.7@conan/stable'
    Version range '>=3.0' required by 'Himalaya/2.0.1@conan/stable' valid for downstream requirement 'eigen/3.3.7@conan/stable'

conanfile.txt: Installing package
Requirements
    Himalaya/2.0.1@conan/stable from 'conan-hep' - Cache
    LoopTools/2.15@conan/stable from 'conan-hep' - Cache
    TSIL/1.44@conan/stable from 'conan-hep' - Cache
    boost/1.70.0@conan/stable from 'conan-center' - Cache
    eigen/3.3.7@conan/stable from 'conan-center' - Cache
Packages
    Himalaya/2.0.1@conan/stable:c302d7be7a18d639806b9c0bb417ea5f6b5614b0 - Build
    LoopTools/2.15@conan/stable:b911f48570f9bb2902d9e83b2b9ebf9d376c8c56 - Build
    TSIL/1.44@conan/stable:ce567d03653ebbd3656fe34042bf2d69b1a53867 - Build
    boost/1.70.0@conan/stable:de3ecc694b0ffb80ed54f7fc8a06e4bba5c89c8c - Build
    eigen/3.3.7@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

gcc-9-1.1.x86_64
Package already installed: gcc
pakiet gfortran nie jest zainstalowany
Running: sudo zypper --non-interactive ref
[sudo] hasło użytkownika root: 
```

**Comment by Expander** [comment]
Hmm, I can't see which package causes this issue. Would you mind running
~~~
conan install . --build=Himalaya -s compiler.libcxx=libstdc++11
conan install . --build=LoopTools -s compiler.libcxx=libstdc++11
~~~

**Comment by wkotlarski** [comment]
Ah, sorry. I think it's `LoopTools`.

**Comment by Expander** [comment]
Ok, thanks for the hint! I'll have a look. Which OS are you using?

**Comment by wkotlarski** [comment]
openSUSE Tumbleweed

**Comment by Expander** [comment]
Do you know the name of the package which contains gfortran? And which package manager do you use? (yum, zypper, ...?)

**Comment by wkotlarski** [comment]
gcc9-fortran. openSUSE uses zypper

**Comment by Expander** [comment]
Thanks! Is there a (meta-)package called `gcc-fortran`?

**Comment by wkotlarski** [comment]
Yes.

**Comment by Expander** [comment]
I think the script should execute this line:
https://github.com/conan-hep/conan-looptools/blob/release/2.15/conanfile.py#L49
The line is executed if `with_pacman` or `with_yum` is true. From you log message, however, it seems that it tries to install `gcc` and `gfortran`. This indicates that the else-branch is taken, i.e. `with_pacman` and `with_yum` are both false. I'll consult the conan documentation to see why both are false. But could it be, that `yum` is not installed on your machine?

**Comment by Expander** [comment]
I've pushed a fix for the issue, see for example 
https://github.com/conan-hep/conan-looptools/commit/2efa5124a92321111d70914e41f9462938f08e56

Would you mind cleaning everything up:
~~~
conan remove LoopTools
conan remove COLLIER
conan remove Himalaya
conan remove TSIL
conan remove Eigen
conan remove Boost
~~~
and then re-run the installation of the FS dependencies via conan (see the build commands in the pull request message above)

**Comment by wkotlarski** [comment]
It works for me now. I'm still confused by `conan` but this is probably because I'm not too familiar with it yet. I had to remove the `~/.conan` dir. After that all went smoothly.

**Comment by Expander** [comment]
Ok. Anyway, many thanks for testing!

**Comment by Expander** [comment]
I've now tested the installation on the RWTH university computers, which run openSUSE. No problems there.

@pathron @jhyeon @azedarach would you mind trying it on your computers?

**Comment by wkotlarski** [comment]
@Expander I think we shouldn't bother @azedarach anymore about stuff not related to decays. I'm leaving a curve out for decays because I still need him :)

**Comment by azedarach** [comment]
I am likely to not be able to help very much with other things, sorry, but this at least takes only 5 minutes :) In my case, running on Ubuntu 18.04 and following the above instructions resulted in a warning about the change in the default C++ ABI and a build failure for Himalaya:
```
Scanning dependencies of target Himalaya_LibraryLink
[ 98%] Building CXX object CMakeFiles/Himalaya_LibraryLink.dir/source/LibraryLink/Himalaya_LibraryLink.cpp.o
[100%] Linking CXX shared module Himalaya_LibraryLink.so
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
CMakeFiles/Himalaya_LibraryLink.dir/build.make:97: recipe for target 'Himalaya_LibraryLink.so' failed
make[2]: *** [Himalaya_LibraryLink.so] Error 1
CMakeFiles/Makefile2:256: recipe for target 'CMakeFiles/Himalaya_LibraryLink.dir/all' failed
make[1]: *** [CMakeFiles/Himalaya_LibraryLink.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Himalaya/2.0.1@conan/stable: 
Himalaya/2.0.1@conan/stable: ERROR: Package '484bd8d09ffa732e920ca6fb6d1ee952bfd72129' build failed
Himalaya/2.0.1@conan/stable: WARN: Build folder /home/dylan/.conan/data/Himalaya/2.0.1/conan/stable/build/484bd8d09ffa732e920ca6fb6d1ee952bfd72129
ERROR: Himalaya/2.0.1@conan/stable: Error in build() method, line 52
	cmake.build()
	ConanException: Error 512 while executing cmake --build '/home/dylan/.conan/data/Himalaya/2.0.1/conan/stable/build/484bd8d09ffa732e920ca6fb6d1ee952bfd72129' '--' '-j8'
```
I am not familiar with conan, so do not know if there is a package available for libuuid - if not, the problem is easily solved by installing using `apt`.

**Comment by Expander** [comment]
@azedarach many thanks for testing! This is in fact a problem with the `FindMathematica.cmake` CMake module shipped with Himalaya. It has been fixed [upstream](https://github.com/sakra/FindMathematica), but this fix is not available in Himalaya 2.0.1. (I'll update it.)

Anyway, if you install libuuid, does the rest work for you?

**Comment by azedarach** [comment]
Yep, after installing libuuid everything works fine.

**Comment by Expander** [comment]
Perfect, thanks!

**Comment by pathron** [comment]
Sorry I have some problems installing conan on my laptop.  I think because I tried first with a very out of date pip and because I have several python versions and left python2 as default.  This is unrelated to anything you do, but I don't have time to fix just now.

I will try to do it on my desktop later today.

**Comment by pathron** [comment]
OK I managed to get conan installed on my desktop.  The first time I tried using it for FS I get errors:

eigen/3.3.7@conan/stable: ERROR: Exception while getting package: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
eigen/3.3.7@conan/stable: ERROR: Exception: <class 'conans.errors.ConanException'> HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0). [Remote: conan-center]
eigen/3.3.7@conan/stable: WARN: Trying to remove package folder: /home/pathron/.conan/data/eigen/3.3.7/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0). [Remote: conan-center]

Probably my connection or the server flaked out.  I just ran the command 

conan install . --build=missing -s compiler.libcxx=libstdc++11

again and everything worked.  This was on ubuntu 16.04.

**Comment by Expander** [comment]
Hi Peter, many thanks for trying!

Yes, the message `HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)` suggests that there was a problem with the connection to the server.

Did you run all the commands, i.e. also `./configure` as described above? Did HSSUSY work in the end?

**Comment by Expander** [comment]
@azedarach I've released Himalaya 2.0.2 and updated the corresponding conan package recipe. Version 2.0.2 checks for libuuid, so I think the problem should be fixed now.

**Comment by pathron** [comment]
@expander yes it worked as expected.

We also discussed this in GAMBIT meeting today and there was some interest.

**Comment by Expander** [comment]
Perfect!
Shall I merger the branch then?

**Comment by pathron** [comment]
Yes!

**Pull request merged**
