### PR TITLE
NPointFunctions: Add Option to choose the excluded Topologies in FeynArts

### PR DESCRIPTION
**Pull request by SoundSonic1**
At the moment, the NPointFunctions module has the FeynArts option `ExcludeTopologies` hardcoded to
`ExcludeTopologies -> Internal`.
This commit makes the option available to the user.
Right now, there is no assertion with regard to the excluded topologies. Maybe someone has a good idea?

@iolojz can you have a look at this?

### CODE REVIEW

**Comment by Expander** [comment]
Please review these changes:
@iolojz
@wkotlarski

**Comment by Expander** [comment]
What would happen if the option `ExcludedTopologies` is not set? Shouldn't a default value be used in this case?

**Comment by SoundSonic1** [comment]
The default is an empty list. So nothing is removed.

**Comment by SoundSonic1** [comment]
Do you want to replace every option of `ExcludeTopologies` with a new one?
There are over 20 options.

**Comment by SoundSonic1** [comment]
@iolojz can you look at the recent commits?

**Comment by Expander** [comment]
Perfect, many thanks!

@wkotlarski , would you mind having a look?

**Comment by wkotlarski** [comment]
I don't use `NPointFunctions` for now, so the changes should not cause any problems for me. Therefore I'm afraid I don't have much to add. Sorry.

**Pull request merged**
