### PR TITLE
enable by default Barr-Zee diagrams

### PR DESCRIPTION
**Pull request by wkotlarski**

### CODE REVIEW

**Comment by Expander** [comment]
Please also adapt the SLHA files in `model_files/` and in particular `templates/LesHouches.in`.

**Comment by wkotlarski** [comment]
Before is start editing gazylion of LesHouches inputs... Is
```
   32   2                    # loop level to calculate AMM
```
this comment ok?

**Comment by Expander** [comment]
Yes, perfect!

**Comment by Expander** [comment]
In the past I've used an `sed` script to avoid doing it manually. You could replace the last line in the `FlexibleSUSY` block
~~~
   31   0                    # loop library (0 = softsusy)
~~~
by itself plus the new comment line:
~~~
   31   0                    # loop library (0 = softsusy)
   32   2                    # loop level to calculate AMM
~~~

**Comment by wkotlarski** [comment]
Done. Ps. Looks like not all files have flag 31. There are 102 `model_files/*/LesHouches.in.*` files, but we made only 78 substitutions.

**Comment by Expander** [comment]
Excellent, thanks a lot! (I hope it was not too painful. :) )

**Review by Expander — APPROVED** [review]

**Pull request merged**
