### PR TITLE
fixing messy cCMSSM test

### PR DESCRIPTION
**Pull request by Expander**
The sign of a neutralino changes between the CMSSM and the cCMSSM

### CODE REVIEW

**Comment by pathron** [comment]
Thanks for doing this! Yes I also see it working now except for the sign of the neutralino mass sign.

Not sure of an easy way to just test the absolute value for that in the approach.  It would be better of we could somehow fix conventions so it comes out positive here.

**Comment by wkotlarski** [comment]
I have a question about neutralino masses. When I ask FS for a mass, will it always be positive? For example, there are places in the decay code where I'd like to write
```c++
if(mIn > mOut1 + mOut2) continue;
```
But if any of the `mIn, mOut1, mOut2` masses is negative, it doesn't work.

**Comment by Expander** [comment]
> When I ask FS for a mass, will it always be positive?

FS uses two conventions:
* The `mass_eigenstates` object uses the Haber-Kane convention. This convention guarantees, that the masses are greater than or equal to 0. However, the mixing matrices are in general complex.
* The `@ModelName@_slha` (which derives from `mass_eigenstates`) uses the SLHA convention. In this conventions the fermion masses may be negative. However, the mixing matrices are guaranteed to be real.

So, it depends on which class you are using.

**Comment by wkotlarski** [comment]
Ok. Thanks a lot. This is consistent with what I'm seeing. We're using `mass_eigenstates` for decays and all masses are positive.

**Review by pathron — APPROVED** [review]
Ok this is fine now, and ready to merge, thanks!

**Comment by Expander** [comment]
Many thanks!

**Pull request merged**
