### PR TITLE
move RT function to new module with decay loop functions

### PR DESCRIPTION
**Pull request by Expander**
in order to improve modularity, testability and reusability

### CODE REVIEW

**Comment by Expander** [comment]
The following functions should also be moved to `src/decay_loop_functions.{hpp,cpp}`:
* `calc_A`
* `calc_DeltaH`
* `calc_DeltaAH`
* `calc_deltaqq`

**Comment by Expander** [comment]
I think it is ready to be merged now, if you agree.

**Comment by wkotlarski** [comment]
Hi @Expander. I'm sorry it took me so long to check your PR. In general I really like your changes. The only problem I have is with the `RT` function.  It's a function for tree-level, three body, single off-shell, decays of h -> VV*. Putting it in `decay_loop_functions.cpp` might be slightly misleading.

**Comment by Expander** [comment]
Sorry, that was not clear to me. I'd propose to move the `RT` function into a separate file, like `decay_tree_functions.cpp`. We may even rename the functions to be more readable:
* `decay_tree_level_functions.cpp`
* `decay_one_loop_functions.cpp`
What do you think?

**Comment by wkotlarski** [comment]
Does it also matter that the loop functions that would go `decay_one_loop_functions.cpp` are not necessarily one-loop functions, but potentially 2 and 3-loop ones?

**Comment by pathron** [comment]
delete 'one' -> decay_loop_functions.cpp

**Comment by Expander** [comment]
Good point: if we call it `decay_loop_functions.cpp`, does this include 0-loop level?

**Pull request merged**
