### PR TITLE
Fj -> Fi V code

### PR DESCRIPTION
**Pull request by wkotlarski**

### CODE REVIEW

**Comment by wkotlarski** [comment]
Any comments? @Expander? @SoundSonic1? @pathron? @jhyeon?

**Comment by SoundSonic1** [comment]
So i have seen some changes to the MRSSM2 model file like implementing the CKM matrix and turning on the observables on by default. Should we revert them or are you okay with this @Expander ?

**Comment by Expander** [comment]
I'm fine with the changes to the MRSSM2 model file.

**Comment by wkotlarski** [comment]
@dhjjacob, you can also comment.

**Comment by dhjjacob** [comment]
I'm all good

**Pull request merged**
