### PR TITLE
Feature b s gamma

### PR DESCRIPTION
**Pull request by wkotlarski**
Here's the code from @SoundSonic1 calculating Wilson coefficient needed for evaluation of b -> s gamma. Currently the code writes to disk a json file for `flavio` and one coefficient to SLHA output. 
Things to note/discuss:
- Any suggestion regarding the output to SLHA file. Should we write all Wilson coefficient there? Or maybe none at all.
- There's a python script reading in Wilson coefficients from the json file and using flavio to compute b to s gamma. Example usage `python3 utils/calc_b_to_s_gamma.py WC_MRSSM2.json`

### CODE REVIEW

**Comment by wkotlarski** [comment]
Should we merge this pull request?

**Comment by Expander** [comment]
Before merging, I have two comments:

1) Could you please add a .rst documentation file? The file should be linked to in the `README.rst` and should include
    * a list of prerequisites (python3, Wilson, flavio, ...)
    * an example step-by-step calculation (listing all the commands)
    * a description of what is included and what is missing (i.e. information about the precision of the calculation)

2) Have you tested that FS compiles with the most common models? The nightly test suite for example checks the following models:
~~~
MSSM
NMSSM
CNMSSM
SMSSM
UMSSM
E6SSM
CE6SSM
MRSSM
MSSMNoFV
U1xMSSM3G
LRLR
minMSSM
rootMSSM
lowMSSM
lowNMSSM
lowNMSSMTanBetaAtMZ
LHInputMSSM
YukawaCMSSM
MSSMRHN
NoYukawaMSSM
NUHMSSM
NUTNMSSM
NUTSMSSM
TMSSM
SM
SSM
NSM
THDMII
THDMIIMSSMBC
THDMIIMSSMBCFull
THDMIIMSSMBCApprox
HTHDMIIMSSMBC
HGTHDMIIMSSMBC
HGTHDMIIMSSMBCFull
HGTHDMIIMSSMBCApprox
SplitMSSM
HSSUSY
MSSMD5O
munuSSM
InertMSSM
CMSSM
MSSMatMGUT
VCMSSM
CMSSMNoFV
MSSMNoFVatMGUT
NUHMSSMNoFV
cSM
BLSM
BLSMlightZp
complexMSSM
cCMSSM
CMSSMCPV
NMSSMCPV
CMSSMCKM
CMSSMLowPrecision
CMSSMMediumPrecision
CMSSMHighPrecision
CMSSMGSLHybrid
CMSSMGSLHybridS
CMSSMGSLBroyden
CMSSMGSLNewton
CMSSMFPIAbsolute
CMSSMFPIRelative
CMSSMFPITadpole
CMSSMMassWInput
CMSSMConvergenceTester
CMSSMMatchedAtMTDRbar
CMSSMMatchedAtMTPole
CMSSMYt2L
MSSMNoEWVEVs
SMHighPrecision
SMnoGUT
SMEWSBAtMZ
SMSU3
MDM
DiracGauginos
MRSSM2
NoInputParameters
BetaSM
MSSMMuBMu
NUHMSSMalt
MSSMCPV
MSSMNoFVHimalaya
MSSMNoFVatMGUTHimalaya
NUHMSSMNoFVHimalaya
SMEFTHiggs
MSSMEFTHiggs
CMSSMEFTHiggs
MSSMNoFVEFTHiggs
NUHMSSMaltEFTHiggs
NMSSMEFTHiggs
MRSSMEFTHiggs
E6SSMEFTHiggs
CMSSMSemiAnalytic
CMSSMCPVSemiAnalytic
lowNUHMSSMSemiAnalytic
munuSSMSemiAnalytic
SMSemiAnalytic
SSMSemiAnalytic
~~~

**Comment by wkotlarski** [comment]
I'm sorry but then this will have to wait. This is not my job and I have to do the stuff I'm paid for before.

**Comment by wkotlarski** [comment]
@Expander, where should be this `rst` file put? There's no precedence. This will be the first such file.

**Comment by Expander** [comment]
I think there are two sensible places:
* `doc/bsgamma.rst`
* `doc/observables/bsgamma.rst`
What do you think?

**Comment by wkotlarski** [comment]
Personally, I like `doc/observables/bsgamma.rst`. About your second point. Currently b to s gamma is computed only for `CMSSMCKM`. All other models are unaffected. And I think we should only compute it for CKM-enabled models. In this PR I've added also a CKM version of MRSSM2.

**Comment by Expander** [comment]
Ok, then let's use `doc/observables/bsgamma.m`. Maybe it would even be sensible to refer to this document like this:

* In `README.rst` link to `doc/observables.rst`
* In `doc/observables.rst` show a list of observables and link to a document for each one, e.g. `doc/observables/bsgamma.m` etc.

**Comment by wkotlarski** [comment]
@Expander could you have a look at [this](https://github.com/wkotlarski/FlexibleSUSY/blob/feature-b-s-gamma/doc/observables.rst). Is this kind of what you had in mind?

**Comment by Expander** [comment]
Very nice! Thanks a lot!

**Comment by wkotlarski** [comment]
@uukhas could you try to follow these instruction [this](https://github.com/wkotlarski/FlexibleSUSY/blob/feature-b-s-gamma/doc/observables/b_physics.rst) and see if everything is clear?

**Comment by uukhas** [comment]
@wkotlarski, one can be a little be more specific in the following:
You suggest to change `FlexibleSUSY.m.in` to calculate this observable, so one can say that the following works. Scenario **I do not have model yet**:

   1. Change `FlexibleSUSY.m.in` for FlexibleSUSY  `<model>`
   2. Run `./createmodel -f --name=<model>` - this will rewrite `FlexibleSUSY.m` in `models/<model>`
   3. Run `./configure <some options> --with-models=<model>`

There is also the second way, which allows to save some time of, i.e. vertex recalculation. Scenarion **I have a model without this observable**:
   1. Assuming that `./createmodel --name=<model>` was typed before one changes `models/<model>/FlexibleSUSY.m` adding this observable.
   2. Then one runs  `./configure <some options> --with-models=<model>`.

Also, there is a misprint in "input", I think.

**Comment by wkotlarski** [comment]
@Expander should we merge it?

**Comment by Expander** [comment]
Could you please add a link to `doc/observables.rst` to the `README.rst` file? I think the section `Further reading` may be a good place.

In addition, could please also add an entry to `CHANGES.rt`?

Afterwards, we can of course merge it!

**Comment by Expander** [comment]
Many thanks! Would you be ok with a "squash and merge"?

**Comment by wkotlarski** [comment]
Yes. I even prefer it.

**Pull request merged**
