### PR TITLE
use pole mass as prefactor in BrLToLGamma

### PR DESCRIPTION
**Pull request by wkotlarski**
Hi @uukhas

I think I've messed up and used a wrong mass as a prefactor. #479 changed the syntax for getting SM lepton masses and before it was easy to make a mistake (it was not super clear which mass is pole and which is not). So I think it was just a typo. Are you ok with this change?

### CODE REVIEW

**Comment by uukhas** [comment]
This is not the only bug that you have introduced in that calculation. The total width calculation is also broken. 
I currently use something like:
```C++
   const auto form_factors = calculate_Fe_Fe_VP_form_factors (generationIndex1, generationIndex2, model, false);
   double leptonInMassOS;
   switch (generationIndex1) {
      case 0: leptonInMassOS = qedqcd.displayMass(softsusy::mElectron); break;
      case 1: leptonInMassOS = qedqcd.displayMass(softsusy::mMuon);     break;
      case 2: leptonInMassOS = qedqcd.displayMass(softsusy::mTau);      break;
      default: throw std::invalid_argument("Unrecognized lepton");
   }
```
for the mass and
```C++
   const double total_width = lepton_total_decay_width<Fe, Fe>(indices1, indices2, model, qedqcd);
```
for the total width.

Look at https://github.com/uukhas/FlexibleSUSY for more details.

**Comment by Expander** [comment]
Just for my understanding: Should the pole or the (running) MS-bar lepton mass be used as prefactor? (Then one should use the corresponding helper function in `QedQcd` that returns the corresponding 3-vector.)

**Comment by uukhas** [comment]
In the 1-loop expressions for amplitudes the running masses are used. 
In the prefactor (derived from the phase space integration) the pole masses are used.

**Comment by Expander** [comment]
OK, then this PR is correct and fixes a bug!

Just for clarity: If the variable `leptonInMassOS` in the code snippet that you've pasted
~~~.cpp
double leptonInMassOS;
switch (generationIndex1) {
   case 0: leptonInMassOS = qedqcd.displayMass(softsusy::mElectron); break;
   case 1: leptonInMassOS = qedqcd.displayMass(softsusy::mMuon);     break;
   case 2: leptonInMassOS = qedqcd.displayMass(softsusy::mTau);      break;
   default: throw std::invalid_argument("Unrecognized lepton");
}
~~~
is supposed to contain the lepton pole mass, then this code snipped contains the same bug and should be fixed in the same way, like so:
~~~.cpp
const double leptonInMassOS = qedqcd.displayLeptonPoleMass(generationIndex1);
~~~

**Comment by pathron** [comment]
No it should give the running mass (this comes from softsusy).

**Comment by pathron** [comment]
line 148,149 of https://github.com/FlexibleSUSY/FlexibleSUSY/blob/fix-use-pole-mass-prefactor-in-llgamma/src/lowe.h

**Comment by Expander** [comment]
> No it should give the running mass (this comes from softsusy).

Yes, `qedqcd.displayMass` returns the running MS-bar mass at the current scale. (The naming is not optimal, as you said, which has historical reasons (the code comes from SOFTSUSY).)

**Comment by pathron** [comment]
Maybe to be precise we should say the running MSbar mass in the SM (with 5 quark flavours if the scale is the scale is above the bottom mass).  Anyway not the BSM running mass just in case that is a point of confusion, though i doubt you would be touching qedqcd object if you wanted running bsm things.

**Comment by uukhas** [comment]
Wow, thanks. Then I agree that this should be changed.
At this point I used this qedqcd for leptons as it was always returning LesHouches input values. 
Maybe I was not precise enough, but it felt like that for all simple checks that I did so far.

**Comment by wkotlarski** [comment]
Can I merge it?

**Review by uukhas — APPROVED** [review]

**Pull request merged**
