### PR TITLE
replace built-in GM2Calc by external package

### PR DESCRIPTION
**Pull request by Expander**
This avoids maintenance of GM2Calc within FlexibleSUSY.

### CODE REVIEW

**Comment by Expander** [comment]
## Summary:

* Removes embedded GM2Calc-code from FlexibleSUSY and replaces it by a dependency

## Pros:
* This avoids maintenance of GM2Calc within FlexibleSUSY (i.e. FS gets GM2Calc updates automatically)
* GM2Calc does no longer have to be enabled by hand via `--with-addons=GM2Calc`, but is enabled automatically inside the `configure` script

## Cons:
* GM2Calc must be installed via conan

**Comment by wkotlarski** [comment]
@Expander, is there a way for conan to install only GM2Calc?

**Comment by Expander** [comment]
Yes, you can run
~~~
conan install GM2Calc/1.7.0@conan/stable
~~~

**Comment by pathron** [comment]
Some comments:

* If I have gm2calc already locally or I don't want to install it via conan, I should be able to pass the path to GM2Calc and then it should work, but I don't see any option to do this.

* I guess just now you assume the user puts in their path, and that is what they should do with conan installed libraries as well?  

* Also while gm2calc is disabled automatically in the configure, if I use --enable-gm2calc configure does not complain and leaves it up to make to fail and indicate it doesn't know where gm2calc is.  I think that is generally how it works with enable- but doesn't seem ideal to me now.

**Comment by Expander** [comment]
Thanks for your feedback!

I have now introduced the possibility for the user to specify the path of the GM2Calc include and library directories. It works now in the same way as for example specifying the paths to the Himalaya directories.

**Comment by pathron** [comment]
Thanks, unfortunately i get errors trying to build this. It worked fine when enabling gm2calc and passing the paths for gm2calc with distributed CMSSM model file . However I think that does not let you use gm2calc with FS?  Following our FS2 manual  i changed model_files/CMSSM/FlexibleSUSY.m 


```
-           {{21, FlexibleSUSYObservable`aMuon} } },
+           {{21, FlexibleSUSYObservable`aMuonGM2Calc} } },

```

and also
 
```
-           {{21, FlexibleSUSYObservable`aMuon} } },
+           {{1,  FlexibleSUSYObservable`aMuonGM2Calc},
+           {2,  FlexibleSUSYObservable`aMuonGM2CalcUncertainty} } },
```


and in both cases I get errors:

```
models/CMSSM_gm2calc/CMSSM_gm2calc_observables.cpp: In function ‘flexiblesusy::CMSSM_gm2calc_observables flexiblesusy::calculate_observables(flexiblesusy::CMSSM_gm2calc_mass_eigenstates&, const softsusy::QedQcd&, const flexiblesusy::Physical_input&)’:
models/CMSSM_gm2calc/CMSSM_gm2calc_observables.cpp:186:49: error: ‘struct flexiblesusy::CMSSM_gm2calc_physical’ has no member named ‘MNull’
       gm2calc_data.MSvm  = MODEL.get_physical().MNull;
                                                 ^~~~~
models/CMSSM_gm2calc/CMSSM_gm2calc_observables.cpp:187:49: error: ‘struct flexiblesusy::CMSSM_gm2calc_physical’ has no member named ‘MNull’
       gm2calc_data.MSm   = MODEL.get_physical().MNull;
                                                 ^~~~~
Makefile:251: recipe for target 'models/CMSSM_gm2calc/CMSSM_gm2calc_observables.o' failed
make: *** [models/CMSSM_gm2calc/CMSSM_gm2calc_observables.o] Error 1
make: *** Waiting for unfinished jobs....
```

By the way there are also no details on how to use gm2calc in the README that i can find, but there is some strange repetition on this as a dependency:
```
The required libraries Boost_, `Eigen 3`_, GM2Calc_, LoopTools_,
Himalaya_ and TSIL_ can be installed using the Conan_ package manager.
If not already installed, Conan can be installed with pip::
The required and optional libraries Boost_, COLLIER_, GM2Calc_, `Eigen
3`_, LoopTools_, Himalaya_ and TSIL_ can be installed using the Conan_
package manager.  If not already installed, Conan can be installed
with pip::
```
Looks like that is an error from a merge.

**Comment by Expander** [comment]
The error
~~~
models/CMSSM_gm2calc/CMSSM_gm2calc_observables.cpp:186:49: error: ‘struct flexiblesusy::CMSSM_gm2calc_physical’ has no member named ‘MNull’
       gm2calc_data.MSvm  = MODEL.get_physical().MNull;
                                                 ^~~~~
~~~
is not specific to this PR. It appears because you're trying to use the GM2Calc extension in a model that has sfermion flavour violation, which is in contrast to the assumptions in GM2Calc. (Specifically, there is no smuon in the CMSSM, only a 6-plet of charged sfermions.) This is why GM2Calc is enabled in the CMSSMNoFV and not in the CMSSM.

To catch this violation of the preconditions, I'll create another PR which fixes this.

**Comment by pathron** [comment]
Yeah I wondered if that was the problem, but I tried with CMSSMNoFV as well and got more errors there, so I got fed up and just posted this.  Does CMSSMNoFV linked with gm2calc work for you?

I think it’s good to catch this rather than through errors, but physically this makes no sense since the FV in the CMSSM is minimal and the only problem is that we don’t identify states as flavour/family  Eigenstates.  I said I some point I should develop a set of translation routines like I did in GAMBIT, we should possibly consider this again.

**Comment by Expander** [comment]
> Yeah I wondered if that was the problem, but I tried with CMSSMNoFV as well and got more errors there, so I got fed up and just posted this. Does CMSSMNoFV linked with gm2calc work for you?

I've fixed some potential linking errors. (Sorry, I've missed them because I was only building using shared libraries.)

> I think it’s good to catch this rather than through errors, but physically this makes no sense since the FV in the CMSSM is minimal and the only problem is that we don’t identify states as flavour/family Eigenstates. I said I some point I should develop a set of translation routines like I did in GAMBIT, we should possibly consider this again.

I see your point. However I think the fact that FV is minimal in the CMSSM is due to the boundary conditions, right? I.e. it is something that is only clear at run-time per parameter point. In other words, based on the structure of the Lagrangian, FS cannot really decide if the FV induced by the model is minimal or not. But I agree with you, caching this error when the meta code runs is a way we should go for now.

**Comment by pathron** [comment]
Its not clear from the Lagrangian, but it should not be clear from the Lagrangian in general, I would say MSSMNoFV is kind of a hack in this sense because you arbitrarily restrict things at the SARAH level.  Though if we think that is the best way to do it, we should put more emphasis on those models.  

The FV violation depends on whether you have include CKM or not and on the BCs, and we know these things when we write the FS model files.  However it is also clear from FCNC limits and fermion mases that in general one expect to a reasobable approximation to  have approximate flavour states for first two generations and just left-right mixing for the third.  It is good that we want to be more general as per slha2 but it is *bad* if we are throwing away a large degree of functionality when the level of FV probably won't affect or invalidate other calculations.   In `@ModelName@_mass_eigenstates.cpp` we already have `calculate_MSu_3rd_generation` etc, so there is actually not much work at all to make available 1st / 2nd flavour masses and 3rd family masses or for g-2 to also include the left-right sefmion mixing for smuons.  We could provide a test on the general sfermion mixing and give a warning if this is larger than we are comfortable with for the gm2calc interface.   I think this is general would be much more precise than using FlexibleAmu for MSSM models.

**Comment by Expander** [comment]
You are right, in this sense the MSSMNoFV is kind of a "hack".

> The FV violation depends on whether you have include CKM or not and on the BCs, and we know these things when we write the FS model files. 

Sorry, but I'm not sure that this is correct. I think even if the CKM matrix is equal to unity, there can still be sfermion flavour violation. (The issue with GM2Calc is not about fermion flavour violation.) For example one can set (in the general MSSM) the 3x3 `mq2` matrix to arbitrary values (as long as it's hermitian), which will induce a mixing between the different sfermion flavours.

I was thinking that in the CMSSM this kind of sfermion flavour violation may be small, because one has at the GUT scale `mq2 = m0^2 * 1`, i.e. at the GUT scale `mq2` is diagonal. If the running does not induce large off-diagonal terms, sfermion flavour may be approximately conserved. (I think similar statements apply to the trilinear couplings.) Maybe I'm misunderstanding something?

Providing these `1st` and `2nd` generation wrapper functions is a great idea! I think this would make the GM2Calc interface much more useful!

**Comment by pathron** [comment]
Er yes... sfermion flavour violation is what I am talking about... “and on the BCs“ refers to removing / including this by the way you set the soft masses.

**Comment by Expander** [comment]
# Summary:

* Removes embedded GM2Calc-code from FlexibleSUSY and replaces it by a dependency

## Pros:

* This avoids maintenance of GM2Calc within FlexibleSUSY (i.e. FS gets GM2Calc updates automatically)
* GM2Calc does no longer have to be enabled by hand via --with-addons=GM2Calc, but is enabled automatically inside the configure script

## Cons:

    GM2Calc must be installed externally (can be done via conan or "by hand")

**Comment by Expander** [comment]
@pathron Are you ok with this change?

**Pull request merged**
