### PR TITLE
Fancy warnings and errors.

### PR DESCRIPTION
**Pull request by uukhas**
With `Mathematica 11` I can suggest to use this simple warning, so that PR #222 might be closed.

### CODE REVIEW

**Comment by wkotlarski** [comment]
Can we make it react to `--enable-colors` option?

**Comment by uukhas** [comment]
I hope that yes. I will think about it. Also, I will apply the solution, if any, to the ``Utils`AssertOrQuit`` (aka "fancy error")

**Comment by uukhas** [comment]
@wkotlarski, now the flag works as expected. I added a new variable with the name `FSColorsAvailable`, which shows on the meta level the setting of `--enable-colors`.

**Comment by wkotlarski** [comment]
Could we maybe rename it to `FSEnableColors`? @Expander, do you have a preference?

**Comment by uukhas** [comment]
I named it as for other variables:
```wolfram
FSFeynArtsAvailable = False;
FSFormCalcAvailable = False;
FSColorsAvailable = False;
```

**Comment by wkotlarski** [comment]
Yes, but FeynArts and FormCalc are external dependencies. So it might make sense to say that they are "available". For colors it sounds odd ;)

**Comment by Expander** [comment]
Personally, I'd also vote for `FSEnableColors`, similarly to `FSEnableParallelism`. Language-wise, `enable-X` means to me that X should be enabled. This is different from `X-avaliable`, which expresses whether X is available on the system (but it does not express if X shall be enabled/used).

**Comment by Expander** [comment]
One question: How would the fancy output look if FS would be run within a Mathematica notebook (not a terminal)?

**Comment by uukhas** [comment]
> One question: How would the fancy output look if FS would be run within a Mathematica notebook (not a terminal)?

Like: 
```
Warning: Some wrapped multiline
         warning string with
^^^^^^^  ______________________
in cyan  length can be changed
```

**Comment by uukhas** [comment]
@Expander,  @wkotlarski, The name is fixed.

**Comment by Expander** [comment]
> > One question: How would the fancy output look if FS would be run within a Mathematica notebook (not a terminal)?
> 
> Like:
> 
> ```
> Warning: Some wrapped multiline
>          warning string.
> ^^^^^^^  ______________________
> in cyan  length can be changed
> ```

Very nice!

**Review by Expander — APPROVED** [review]

**Comment by wkotlarski** [comment]
Simple test
```diff
diff --git a/meta/FFVFormFactors.m b/meta/FFVFormFactors.m
index 36c82192c..a24841723 100644
--- a/meta/FFVFormFactors.m
+++ b/meta/FFVFormFactors.m
@@ -89,7 +89,7 @@ IsDiagramSupported[graph_, diagram_] :=
          Return[True]
       ];
 
-      Print["Warning: Diagram with internal particles of type ",
+      Utils`FSFancyWarning["Diagram with internal particles of type " <>
          StringJoin @@ (ToString /@ SARAH`getType /@ {EmitterL[diagram], EmitterR[diagram], Spectator[diagram]})];
       Print["         is currently not supported."];
       Print["         Discarding diagram with particles ",
```
From this I get doubled lines
```
Warning: Diagram with internal particles of type FFV
Warning: Diagram with internal particles of type FFV
```
I'm I using it wrong?

**Comment by uukhas** [comment]
@wkotlarski, it seems that you are doing things normally :) 
I have duplicated some command during previous fix - this was the reason of the problem.

**Comment by wkotlarski** [comment]
Perfect. Thanks! Now it works as expected. One last thing. @Expander, @uukhas, can we discuss the choice of colours? Vova choose cyan for warning. My personal preference would maybe be yellow or orange. What do you think?

**Comment by uukhas** [comment]
I would love to make one separate `.m` file with list of all global variables, which we use.
It can contain
* the width of fancy lines, 
* the width of output text,
* default indentation string,
* color for warnings,
* color for errors
* ... something else 

The reason is the following: now we have too many of them and they live hard-coded in separate files. Having the one file, named something like `Globals.m` would simplify development and increase modularity.

**Comment by uukhas** [comment]
> Perfect. Thanks! Now it works as expected. One last thing. @Expander, @uukhas, can we discuss the choice of colours? Vova choose cyan for warning. My personal preference would maybe be yellow or orange. What do you think?

I am okay with any option. We can change it any time in the future anyways.

**Review by wkotlarski — APPROVED** [review]

**Pull request merged**
