### PR TITLE
break dependency on slhaea.h

### PR DESCRIPTION
**Pull request by Expander**
This avoids large pieces of transitive dependencies on boost and STL headers

### CODE REVIEW

**Comment by Expander** [comment]
@wkotlarski would you mind checking that this change is not in conflict with your developments in the decays branch?

(It is not, if you are not explicitly using `SLHAea::Coll` etc. If you do so, it should be refactored such that the dependency on `SLHAea::Coll` etc. is removed.)

**Comment by wkotlarski** [comment]
Dylan introduced few functions that use it. For example in `mea/WriteOut.m` we now have
```mathematica
CreateFillSLHAeaIncludingDecaysPrototypes[modelName_String] := "\
template <class Model>
static void fill_slhaea(
   SLHAea::Coll&, const " <> modelName <> "_slha<Model>&, const softsusy::QedQcd&,
   const " <> modelName <> "_scales&, const " <> modelName <> "_observables&,
   const " <> modelName <> "_decays&);
```

**Comment by Expander** [comment]
I have removed/changed an equivalent function just recently, see commit bb02f70fed663 . This function was only used in `run_cmd_line.cpp.in` and was replaced by `@ModelName@_slha_io::fill(...)`. I believe an equivalent change can be made to the decays branch.

**Comment by Expander** [comment]
If these functions are a problem, I can help rewriting them.

**Comment by wkotlarski** [comment]
Please merge it. I'll adopt decay then.

**Comment by Expander** [comment]
Thanks a lot!

**Pull request merged**
